package project

import "fmt"

// hasCapability reports whether name is present in capabilities.
func hasCapability(capabilities []string, name string) bool {
	for _, c := range capabilities {
		if c == name {
			return true
		}
	}
	return false
}

// buildCapabilityConfig is the default capability_config["build"] value
// project create writes when the "build" capability is enabled - engine
// defaults to bazel (v1 implementation, docs/spec/build-adapter/README.md),
// target_patterns default to the whole project subtree. This is generated,
// never hand-authored (principle 8, anti-Boq, §2.3): a project never needs
// a human to write this block to get build-graph refinement working.
func buildCapabilityConfig(projectPath string) map[string]interface{} {
	return map[string]interface{}{
		"engine":          "bazel",
		"target_patterns": []string{fmt.Sprintf("//%s/...", projectPath)},
	}
}

// buildCapabilityFiles generates the BUILD.bazel wiring for the greenfield
// golden path (docs/design.md §14.5.4): "project create emits generated
// BUILD wiring ... with zero hand-authored BUILD lines". Content is
// deliberately minimal - a filegroup covering the whole project directory -
// since language-specific rules (go_library, py_library, ...) are an
// org-specific template concern this core package doesn't own.
func buildCapabilityFiles(projectPath string) []FileWrite {
	content := fmt.Sprintf(`# Generated by "runko project create" (build capability, docs/design.md
# §14.5.4). Target pattern for this project: //%s/...
#
# Org-specific language rules (go_library, py_library, ...) layer on top via
# org templates - this file is deliberately minimal so create_project never
# requires hand-authored BUILD content (principle 8, anti-Boq, §2.3).

filegroup(
    name = "srcs",
    srcs = glob(["**/*"], exclude = ["BUILD.bazel"]),
    visibility = ["//visibility:public"],
)
`, projectPath)
	return []FileWrite{{Path: "BUILD.bazel", Action: "create", Content: content}}
}
