package project

import "fmt"

// hasCapability reports whether name is present in capabilities.
func hasCapability(capabilities []string, name string) bool {
	for _, c := range capabilities {
		if c == name {
			return true
		}
	}
	return false
}

// Build-engine selection at create time (docs/design.md §14.5.5, decided
// 2026-07-09). "bazel" is a real engine (§14.5.4 admission criteria:
// declared targets, hermetic at a SHA, rdeps) and gets the
// capability_config.build binding; "vite" is a TERRITORY SCAFFOLD, not an
// engine - it deliberately gets no `build` capability and no binding, its
// territory rides the declared affected floor; "none" scaffolds nothing.
const (
	BuildEngineBazel = "bazel"
	BuildEngineVite  = "vite"
	BuildEngineNone  = "none"
)

// BuildEngines is the declarable set, for error messages and UI pickers.
var BuildEngines = []string{BuildEngineBazel, BuildEngineVite, BuildEngineNone}

// DefaultBuildEngine is the language default (§14.5.5): ts territories get
// Vite (Bazel's dev-loop economics are structurally wrong for frontend -
// hermetic sandboxed actions vs an in-memory HMR module graph), everything
// else gets the Bazel golden path. no_template intents keep bazel
// regardless of language: the generated filegroup is language-agnostic.
func DefaultBuildEngine(language string, noTemplate bool) string {
	if language == "ts" && !noTemplate {
		return BuildEngineVite
	}
	return BuildEngineBazel
}

// buildCapabilityConfig is the default capability_config["build"] value
// project create writes when the "build" capability is enabled - engine
// defaults to bazel (v1 implementation, docs/spec/build-adapter/README.md),
// target_patterns default to the whole project subtree. This is generated,
// never hand-authored (principle 8, anti-Boq, §2.3): a project never needs
// a human to write this block to get build-graph refinement working.
func buildCapabilityConfig(projectPath string) map[string]interface{} {
	return map[string]interface{}{
		"engine":          "bazel",
		"target_patterns": []string{fmt.Sprintf("//%s/...", projectPath)},
	}
}

// buildCapabilityFiles generates the BUILD.bazel wiring for the greenfield
// golden path (docs/design.md §14.5.4): "project create emits generated
// BUILD wiring ... with zero hand-authored BUILD lines". Content is
// deliberately minimal - a filegroup covering the whole project directory -
// since language-specific rules (go_library, py_library, ...) are an
// org-specific template concern this core package doesn't own.
func buildCapabilityFiles(projectPath string) []FileWrite {
	content := fmt.Sprintf(`# Generated by "runko project create" (build capability).
# Target pattern for this project: //%s/...
#
# Org-specific language rules (go_library, py_library, ...) layer on top via
# org templates - this file is deliberately minimal so create_project never
# requires hand-authored BUILD content.

filegroup(
    name = "srcs",
    srcs = glob(["**/*"], exclude = ["BUILD.bazel"]),
    visibility = ["//visibility:public"],
)
`, projectPath)
	return []FileWrite{{Path: "BUILD.bazel", Action: "create", Content: content}}
}

// viteScaffoldFiles is the vite territory's graph-node marker (§14.5.5):
// the js-tooling equivalent of BUILD.bazel. The one sanctioned exception
// to §10.4's "no package.json in built-ins" rule - for a Vite territory,
// package.json IS the build declaration. Still no tsconfig/lockfile:
// toolchain config beyond the marker stays an org-template concern.
func viteScaffoldFiles(projectName string) []FileWrite {
	pkg := fmt.Sprintf(`{
  "name": %q,
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^8"
  }
}
`, projectName)
	config := `// Generated by "runko project create" (build_engine: vite).
// Vite is a territory scaffold, not a build-graph engine - this project
// rides the declared affected floor; there is no capability_config.build
// binding to keep in sync.
export default {};
`
	return []FileWrite{
		{Path: "package.json", Action: "create", Content: pkg},
		{Path: "vite.config.ts", Action: "create", Content: config},
	}
}

// withoutCapability returns capabilities minus name, preserving order.
func withoutCapability(capabilities []string, name string) []string {
	out := make([]string, 0, len(capabilities))
	for _, c := range capabilities {
		if c != name {
			out = append(out, c)
		}
	}
	return out
}
