// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actors.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentPolicy = `-- name: CreateAgentPolicy :one
INSERT INTO agent_policies (
    org_id, name, require_workspace_affinity, max_changed_files, max_diff_bytes,
    can_create_projects, can_land_changes, can_modify_owners, can_enable_capabilities, denylist_paths
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, org_id, name, require_workspace_affinity, max_changed_files, max_diff_bytes, can_create_projects, can_land_changes, can_modify_owners, can_enable_capabilities, denylist_paths, created_at, require_description, updated_by, updated_at
`

type CreateAgentPolicyParams struct {
	OrgID                    uuid.UUID `json:"org_id"`
	Name                     string    `json:"name"`
	RequireWorkspaceAffinity bool      `json:"require_workspace_affinity"`
	MaxChangedFiles          int32     `json:"max_changed_files"`
	MaxDiffBytes             int64     `json:"max_diff_bytes"`
	CanCreateProjects        bool      `json:"can_create_projects"`
	CanLandChanges           bool      `json:"can_land_changes"`
	CanModifyOwners          bool      `json:"can_modify_owners"`
	CanEnableCapabilities    []string  `json:"can_enable_capabilities"`
	DenylistPaths            []string  `json:"denylist_paths"`
}

func (q *Queries) CreateAgentPolicy(ctx context.Context, db DBTX, arg CreateAgentPolicyParams) (*AgentPolicy, error) {
	row := db.QueryRow(ctx, createAgentPolicy,
		arg.OrgID,
		arg.Name,
		arg.RequireWorkspaceAffinity,
		arg.MaxChangedFiles,
		arg.MaxDiffBytes,
		arg.CanCreateProjects,
		arg.CanLandChanges,
		arg.CanModifyOwners,
		arg.CanEnableCapabilities,
		arg.DenylistPaths,
	)
	var i AgentPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.RequireWorkspaceAffinity,
		&i.MaxChangedFiles,
		&i.MaxDiffBytes,
		&i.CanCreateProjects,
		&i.CanLandChanges,
		&i.CanModifyOwners,
		&i.CanEnableCapabilities,
		&i.DenylistPaths,
		&i.CreatedAt,
		&i.RequireDescription,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const getActor = `-- name: GetActor :one
SELECT id, org_id, type, external_ref, display_name, agent_policy_id, metadata, created_at FROM actors WHERE id = $1
`

func (q *Queries) GetActor(ctx context.Context, db DBTX, id uuid.UUID) (*Actor, error) {
	row := db.QueryRow(ctx, getActor, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.ExternalRef,
		&i.DisplayName,
		&i.AgentPolicyID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return &i, err
}

const getActorByExternalRef = `-- name: GetActorByExternalRef :one
SELECT id, org_id, type, external_ref, display_name, agent_policy_id, metadata, created_at FROM actors WHERE org_id = $1 AND type = $2 AND external_ref = $3
`

type GetActorByExternalRefParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	Type        ActorType `json:"type"`
	ExternalRef string    `json:"external_ref"`
}

func (q *Queries) GetActorByExternalRef(ctx context.Context, db DBTX, arg GetActorByExternalRefParams) (*Actor, error) {
	row := db.QueryRow(ctx, getActorByExternalRef, arg.OrgID, arg.Type, arg.ExternalRef)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.ExternalRef,
		&i.DisplayName,
		&i.AgentPolicyID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return &i, err
}

const getActorsByIDs = `-- name: GetActorsByIDs :many
SELECT id, org_id, type, external_ref, display_name, agent_policy_id, metadata, created_at FROM actors WHERE id = ANY($1::uuid[])
`

// Batch form of GetActor for list hydration: ListChanges used to resolve
// authored_by/landed_by with one GetActor round-trip per row (N+1 - the
// landed tab's 300ms at 44 changes), this fetches every distinct actor a
// page of changes references in one query.
func (q *Queries) GetActorsByIDs(ctx context.Context, db DBTX, ids []uuid.UUID) ([]*Actor, error) {
	rows, err := db.Query(ctx, getActorsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Actor
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.ExternalRef,
			&i.DisplayName,
			&i.AgentPolicyID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentPolicy = `-- name: GetAgentPolicy :one
SELECT id, org_id, name, require_workspace_affinity, max_changed_files, max_diff_bytes, can_create_projects, can_land_changes, can_modify_owners, can_enable_capabilities, denylist_paths, created_at, require_description, updated_by, updated_at FROM agent_policies WHERE id = $1
`

func (q *Queries) GetAgentPolicy(ctx context.Context, db DBTX, id uuid.UUID) (*AgentPolicy, error) {
	row := db.QueryRow(ctx, getAgentPolicy, id)
	var i AgentPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.RequireWorkspaceAffinity,
		&i.MaxChangedFiles,
		&i.MaxDiffBytes,
		&i.CanCreateProjects,
		&i.CanLandChanges,
		&i.CanModifyOwners,
		&i.CanEnableCapabilities,
		&i.DenylistPaths,
		&i.CreatedAt,
		&i.RequireDescription,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAgentPolicyByName = `-- name: GetAgentPolicyByName :one
SELECT id, org_id, name, require_workspace_affinity, max_changed_files, max_diff_bytes, can_create_projects, can_land_changes, can_modify_owners, can_enable_capabilities, denylist_paths, created_at, require_description, updated_by, updated_at FROM agent_policies WHERE org_id = $1 AND name = $2
`

type GetAgentPolicyByNameParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) GetAgentPolicyByName(ctx context.Context, db DBTX, arg GetAgentPolicyByNameParams) (*AgentPolicy, error) {
	row := db.QueryRow(ctx, getAgentPolicyByName, arg.OrgID, arg.Name)
	var i AgentPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.RequireWorkspaceAffinity,
		&i.MaxChangedFiles,
		&i.MaxDiffBytes,
		&i.CanCreateProjects,
		&i.CanLandChanges,
		&i.CanModifyOwners,
		&i.CanEnableCapabilities,
		&i.DenylistPaths,
		&i.CreatedAt,
		&i.RequireDescription,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertActor = `-- name: UpsertActor :one
INSERT INTO actors (org_id, type, external_ref, display_name, agent_policy_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (org_id, type, external_ref) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        agent_policy_id = EXCLUDED.agent_policy_id,
        metadata = EXCLUDED.metadata
RETURNING id, org_id, type, external_ref, display_name, agent_policy_id, metadata, created_at
`

type UpsertActorParams struct {
	OrgID         uuid.UUID   `json:"org_id"`
	Type          ActorType   `json:"type"`
	ExternalRef   string      `json:"external_ref"`
	DisplayName   *string     `json:"display_name"`
	AgentPolicyID pgtype.UUID `json:"agent_policy_id"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) UpsertActor(ctx context.Context, db DBTX, arg UpsertActorParams) (*Actor, error) {
	row := db.QueryRow(ctx, upsertActor,
		arg.OrgID,
		arg.Type,
		arg.ExternalRef,
		arg.DisplayName,
		arg.AgentPolicyID,
		arg.Metadata,
	)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.ExternalRef,
		&i.DisplayName,
		&i.AgentPolicyID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return &i, err
}
