// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agentprincipals.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredAgentPrincipals = `-- name: DeleteExpiredAgentPrincipals :exec
DELETE FROM agent_principals WHERE org_id = $1 AND expires_at < $2
`

type DeleteExpiredAgentPrincipalsParams struct {
	OrgID     uuid.UUID          `json:"org_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Opportunistic hygiene (run at mint time): credentials dead for over the
// grace window carry no auth value - attribution lives in actors rows, not
// here - so the table never grows with history.
func (q *Queries) DeleteExpiredAgentPrincipals(ctx context.Context, db DBTX, arg DeleteExpiredAgentPrincipalsParams) error {
	_, err := db.Exec(ctx, deleteExpiredAgentPrincipals, arg.OrgID, arg.ExpiresAt)
	return err
}

const getAgentPrincipalByName = `-- name: GetAgentPrincipalByName :one
SELECT id, org_id, name, task, token_hash, created_by, created_at, expires_at, revoked FROM agent_principals WHERE org_id = $1 AND name = $2
`

type GetAgentPrincipalByNameParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) GetAgentPrincipalByName(ctx context.Context, db DBTX, arg GetAgentPrincipalByNameParams) (*AgentPrincipal, error) {
	row := db.QueryRow(ctx, getAgentPrincipalByName, arg.OrgID, arg.Name)
	var i AgentPrincipal
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Task,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return &i, err
}

const getAgentPrincipalByTokenHash = `-- name: GetAgentPrincipalByTokenHash :one
SELECT id, org_id, name, task, token_hash, created_by, created_at, expires_at, revoked FROM agent_principals WHERE org_id = $1 AND token_hash = $2
`

type GetAgentPrincipalByTokenHashParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) GetAgentPrincipalByTokenHash(ctx context.Context, db DBTX, arg GetAgentPrincipalByTokenHashParams) (*AgentPrincipal, error) {
	row := db.QueryRow(ctx, getAgentPrincipalByTokenHash, arg.OrgID, arg.TokenHash)
	var i AgentPrincipal
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Task,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return &i, err
}

const listAgentPrincipals = `-- name: ListAgentPrincipals :many
SELECT id, org_id, name, task, token_hash, created_by, created_at, expires_at, revoked FROM agent_principals WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAgentPrincipals(ctx context.Context, db DBTX, orgID uuid.UUID) ([]*AgentPrincipal, error) {
	rows, err := db.Query(ctx, listAgentPrincipals, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AgentPrincipal
	for rows.Next() {
		var i AgentPrincipal
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Task,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mintAgentPrincipal = `-- name: MintAgentPrincipal :one
INSERT INTO agent_principals (org_id, name, task, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, org_id, name, task, token_hash, created_by, created_at, expires_at, revoked
`

type MintAgentPrincipalParams struct {
	OrgID     uuid.UUID          `json:"org_id"`
	Name      string             `json:"name"`
	Task      string             `json:"task"`
	TokenHash string             `json:"token_hash"`
	CreatedBy string             `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) MintAgentPrincipal(ctx context.Context, db DBTX, arg MintAgentPrincipalParams) (*AgentPrincipal, error) {
	row := db.QueryRow(ctx, mintAgentPrincipal,
		arg.OrgID,
		arg.Name,
		arg.Task,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i AgentPrincipal
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Task,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return &i, err
}

const revokeAgentPrincipal = `-- name: RevokeAgentPrincipal :exec
UPDATE agent_principals SET revoked = true WHERE org_id = $1 AND name = $2
`

type RevokeAgentPrincipalParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) RevokeAgentPrincipal(ctx context.Context, db DBTX, arg RevokeAgentPrincipalParams) error {
	_, err := db.Exec(ctx, revokeAgentPrincipal, arg.OrgID, arg.Name)
	return err
}
