// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_policies.sql

package dbgen

import (
	"context"
)

const deleteAgentPolicyForOrg = `-- name: DeleteAgentPolicyForOrg :exec
DELETE FROM agent_policies ap USING orgs o
WHERE ap.org_id = o.id AND o.name = $1::text AND ap.name = $2::text
`

type DeleteAgentPolicyForOrgParams struct {
	OrgName string `json:"org_name"`
	Name    string `json:"name"`
}

// --reset: drop the override row so DefaultAgentPolicy() applies again.
func (q *Queries) DeleteAgentPolicyForOrg(ctx context.Context, db DBTX, arg DeleteAgentPolicyForOrgParams) error {
	_, err := db.Exec(ctx, deleteAgentPolicyForOrg, arg.OrgName, arg.Name)
	return err
}

const getAgentPolicyForOrg = `-- name: GetAgentPolicyForOrg :one

SELECT ap.id, ap.org_id, ap.name, ap.require_workspace_affinity, ap.max_changed_files, ap.max_diff_bytes, ap.can_create_projects, ap.can_land_changes, ap.can_modify_owners, ap.can_enable_capabilities, ap.denylist_paths, ap.created_at, ap.require_description, ap.updated_by, ap.updated_at FROM agent_policies ap
JOIN orgs o ON o.id = ap.org_id
WHERE o.name = $1::text AND ap.name = $2::text
`

type GetAgentPolicyForOrgParams struct {
	OrgName string `json:"org_name"`
	Name    string `json:"name"`
}

// Per-org agent policy overrides (§8.7): the persisted, operator-tunable form
// of receive.AgentPolicy, keyed by org NAME (like GetOrgSettings) + policy name
// (” = the org-wide policy; per-agent names are a future layer, and the schema
// already carries actors.agent_policy_id for it). Absent -> DefaultAgentPolicy()
// applies, so a fresh org stays locked down. Only operators write these.
// The by-id / by-org_id queries in actors.sql predate this and stay for the
// actor-binding path.
func (q *Queries) GetAgentPolicyForOrg(ctx context.Context, db DBTX, arg GetAgentPolicyForOrgParams) (*AgentPolicy, error) {
	row := db.QueryRow(ctx, getAgentPolicyForOrg, arg.OrgName, arg.Name)
	var i AgentPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.RequireWorkspaceAffinity,
		&i.MaxChangedFiles,
		&i.MaxDiffBytes,
		&i.CanCreateProjects,
		&i.CanLandChanges,
		&i.CanModifyOwners,
		&i.CanEnableCapabilities,
		&i.DenylistPaths,
		&i.CreatedAt,
		&i.RequireDescription,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertAgentPolicyForOrg = `-- name: UpsertAgentPolicyForOrg :exec
INSERT INTO agent_policies (
    org_id, name, require_workspace_affinity, require_description, max_changed_files,
    max_diff_bytes, can_create_projects, can_land_changes, can_modify_owners,
    can_enable_capabilities, denylist_paths, updated_by, updated_at
)
SELECT o.id, $1::text, $2::boolean,
    $3::boolean, $4::int,
    $5::bigint, $6::boolean,
    $7::boolean, $8::boolean,
    $9::text[], $10::text[],
    $11::text, now()
FROM orgs o WHERE o.name = $12::text
ON CONFLICT (org_id, name) DO UPDATE SET
    require_workspace_affinity = EXCLUDED.require_workspace_affinity,
    require_description = EXCLUDED.require_description,
    max_changed_files = EXCLUDED.max_changed_files,
    max_diff_bytes = EXCLUDED.max_diff_bytes,
    can_create_projects = EXCLUDED.can_create_projects,
    can_land_changes = EXCLUDED.can_land_changes,
    can_modify_owners = EXCLUDED.can_modify_owners,
    can_enable_capabilities = EXCLUDED.can_enable_capabilities,
    denylist_paths = EXCLUDED.denylist_paths,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
`

type UpsertAgentPolicyForOrgParams struct {
	Name                     string   `json:"name"`
	RequireWorkspaceAffinity bool     `json:"require_workspace_affinity"`
	RequireDescription       bool     `json:"require_description"`
	MaxChangedFiles          int32    `json:"max_changed_files"`
	MaxDiffBytes             int64    `json:"max_diff_bytes"`
	CanCreateProjects        bool     `json:"can_create_projects"`
	CanLandChanges           bool     `json:"can_land_changes"`
	CanModifyOwners          bool     `json:"can_modify_owners"`
	CanEnableCapabilities    []string `json:"can_enable_capabilities"`
	DenylistPaths            []string `json:"denylist_paths"`
	UpdatedBy                string   `json:"updated_by"`
	OrgName                  string   `json:"org_name"`
}

// The CLI writes a COMPLETE policy (read-modify-write of the effective policy),
// so every column is set; there is no partial-field merge here. A future
// AgentPolicy field is a new column with a safe migration default, inherited by
// existing rows - so stored policies never silently freeze to an unsafe zero.
func (q *Queries) UpsertAgentPolicyForOrg(ctx context.Context, db DBTX, arg UpsertAgentPolicyForOrgParams) error {
	_, err := db.Exec(ctx, upsertAgentPolicyForOrg,
		arg.Name,
		arg.RequireWorkspaceAffinity,
		arg.RequireDescription,
		arg.MaxChangedFiles,
		arg.MaxDiffBytes,
		arg.CanCreateProjects,
		arg.CanLandChanges,
		arg.CanModifyOwners,
		arg.CanEnableCapabilities,
		arg.DenylistPaths,
		arg.UpdatedBy,
		arg.OrgName,
	)
	return err
}
