// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changes.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abandonChange = `-- name: AbandonChange :one
UPDATE changes SET state = 'abandoned', updated_at = now() WHERE id = $1 RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by
`

func (q *Queries) AbandonChange(ctx context.Context, db DBTX, id uuid.UUID) (*Change, error) {
	row := db.QueryRow(ctx, abandonChange, id)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
		&i.LandedByActorID,
		&i.OriginWorkspace,
		&i.OriginBranch,
		&i.LandedForced,
		&i.Automerge,
		&i.AutomergeBy,
	)
	return &i, err
}

const addChangeAffectedProject = `-- name: AddChangeAffectedProject :exec
INSERT INTO change_affected_projects (change_affected_id, project_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddChangeAffectedProjectParams struct {
	ChangeAffectedID uuid.UUID `json:"change_affected_id"`
	ProjectID        uuid.UUID `json:"project_id"`
}

func (q *Queries) AddChangeAffectedProject(ctx context.Context, db DBTX, arg AddChangeAffectedProjectParams) error {
	_, err := db.Exec(ctx, addChangeAffectedProject, arg.ChangeAffectedID, arg.ProjectID)
	return err
}

const addChangeAssistedBy = `-- name: AddChangeAssistedBy :exec
INSERT INTO change_assisted_by (change_id, actor_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddChangeAssistedByParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	ActorID  uuid.UUID `json:"actor_id"`
}

func (q *Queries) AddChangeAssistedBy(ctx context.Context, db DBTX, arg AddChangeAssistedByParams) error {
	_, err := db.Exec(ctx, addChangeAssistedBy, arg.ChangeID, arg.ActorID)
	return err
}

const createChange = `-- name: CreateChange :one
INSERT INTO changes (
    monorepo_id, change_key, state, base_sha, head_sha, git_ref, title,
    description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical,
    origin_workspace, origin_branch
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by
`

type CreateChangeParams struct {
	MonorepoID        uuid.UUID   `json:"monorepo_id"`
	ChangeKey         string      `json:"change_key"`
	State             ChangeState `json:"state"`
	BaseSha           string      `json:"base_sha"`
	HeadSha           string      `json:"head_sha"`
	GitRef            string      `json:"git_ref"`
	Title             string      `json:"title"`
	Description       string      `json:"description"`
	TestPlan          string      `json:"test_plan"`
	AuthoredByActorID uuid.UUID   `json:"authored_by_actor_id"`
	DependsOnChangeID pgtype.UUID `json:"depends_on_change_id"`
	Mechanical        bool        `json:"mechanical"`
	OriginWorkspace   string      `json:"origin_workspace"`
	OriginBranch      string      `json:"origin_branch"`
}

func (q *Queries) CreateChange(ctx context.Context, db DBTX, arg CreateChangeParams) (*Change, error) {
	row := db.QueryRow(ctx, createChange,
		arg.MonorepoID,
		arg.ChangeKey,
		arg.State,
		arg.BaseSha,
		arg.HeadSha,
		arg.GitRef,
		arg.Title,
		arg.Description,
		arg.TestPlan,
		arg.AuthoredByActorID,
		arg.DependsOnChangeID,
		arg.Mechanical,
		arg.OriginWorkspace,
		arg.OriginBranch,
	)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
		&i.LandedByActorID,
		&i.OriginWorkspace,
		&i.OriginBranch,
		&i.LandedForced,
		&i.Automerge,
		&i.AutomergeBy,
	)
	return &i, err
}

const createChangeComment = `-- name: CreateChangeComment :one
INSERT INTO change_comments (change_id, author_actor_id, body, path, line, side, head_sha, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, change_id, author_actor_id, body, path, line, created_at, head_sha, side, parent_id, resolved
`

type CreateChangeCommentParams struct {
	ChangeID      uuid.UUID   `json:"change_id"`
	AuthorActorID uuid.UUID   `json:"author_actor_id"`
	Body          string      `json:"body"`
	Path          *string     `json:"path"`
	Line          *int32      `json:"line"`
	Side          *string     `json:"side"`
	HeadSha       *string     `json:"head_sha"`
	ParentID      pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateChangeComment(ctx context.Context, db DBTX, arg CreateChangeCommentParams) (*ChangeComment, error) {
	row := db.QueryRow(ctx, createChangeComment,
		arg.ChangeID,
		arg.AuthorActorID,
		arg.Body,
		arg.Path,
		arg.Line,
		arg.Side,
		arg.HeadSha,
		arg.ParentID,
	)
	var i ChangeComment
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.AuthorActorID,
		&i.Body,
		&i.Path,
		&i.Line,
		&i.CreatedAt,
		&i.HeadSha,
		&i.Side,
		&i.ParentID,
		&i.Resolved,
	)
	return &i, err
}

const getChange = `-- name: GetChange :one
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE id = $1
`

func (q *Queries) GetChange(ctx context.Context, db DBTX, id uuid.UUID) (*Change, error) {
	row := db.QueryRow(ctx, getChange, id)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
		&i.LandedByActorID,
		&i.OriginWorkspace,
		&i.OriginBranch,
		&i.LandedForced,
		&i.Automerge,
		&i.AutomergeBy,
	)
	return &i, err
}

const getChangeAffected = `-- name: GetChangeAffected :one
SELECT id, change_id, head_sha, computation_id, run_everything, reason_codes, computed_at FROM change_affected WHERE change_id = $1 AND head_sha = $2
`

type GetChangeAffectedParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	HeadSha  string    `json:"head_sha"`
}

func (q *Queries) GetChangeAffected(ctx context.Context, db DBTX, arg GetChangeAffectedParams) (*ChangeAffected, error) {
	row := db.QueryRow(ctx, getChangeAffected, arg.ChangeID, arg.HeadSha)
	var i ChangeAffected
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.HeadSha,
		&i.ComputationID,
		&i.RunEverything,
		&i.ReasonCodes,
		&i.ComputedAt,
	)
	return &i, err
}

const getChangeByKey = `-- name: GetChangeByKey :one
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE monorepo_id = $1 AND change_key = $2
`

type GetChangeByKeyParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	ChangeKey  string    `json:"change_key"`
}

func (q *Queries) GetChangeByKey(ctx context.Context, db DBTX, arg GetChangeByKeyParams) (*Change, error) {
	row := db.QueryRow(ctx, getChangeByKey, arg.MonorepoID, arg.ChangeKey)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
		&i.LandedByActorID,
		&i.OriginWorkspace,
		&i.OriginBranch,
		&i.LandedForced,
		&i.Automerge,
		&i.AutomergeBy,
	)
	return &i, err
}

const getChangeComment = `-- name: GetChangeComment :one
SELECT id, change_id, author_actor_id, body, path, line, created_at, head_sha, side, parent_id, resolved FROM change_comments WHERE id = $1 AND change_id = $2
`

type GetChangeCommentParams struct {
	ID       uuid.UUID `json:"id"`
	ChangeID uuid.UUID `json:"change_id"`
}

func (q *Queries) GetChangeComment(ctx context.Context, db DBTX, arg GetChangeCommentParams) (*ChangeComment, error) {
	row := db.QueryRow(ctx, getChangeComment, arg.ID, arg.ChangeID)
	var i ChangeComment
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.AuthorActorID,
		&i.Body,
		&i.Path,
		&i.Line,
		&i.CreatedAt,
		&i.HeadSha,
		&i.Side,
		&i.ParentID,
		&i.Resolved,
	)
	return &i, err
}

const landChange = `-- name: LandChange :one
UPDATE changes SET state = 'landed', landed_at = now(), landed_sha = $2, landed_by_actor_id = $3,
    landed_forced = $4::boolean, updated_at = now()
WHERE id = $1 RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by
`

type LandChangeParams struct {
	ID              uuid.UUID   `json:"id"`
	LandedSha       *string     `json:"landed_sha"`
	LandedByActorID pgtype.UUID `json:"landed_by_actor_id"`
	LandedForced    bool        `json:"landed_forced"`
}

func (q *Queries) LandChange(ctx context.Context, db DBTX, arg LandChangeParams) (*Change, error) {
	row := db.QueryRow(ctx, landChange,
		arg.ID,
		arg.LandedSha,
		arg.LandedByActorID,
		arg.LandedForced,
	)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
		&i.LandedByActorID,
		&i.OriginWorkspace,
		&i.OriginBranch,
		&i.LandedForced,
		&i.Automerge,
		&i.AutomergeBy,
	)
	return &i, err
}

const listAllChanges = `-- name: ListAllChanges :many
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE monorepo_id = $1 ORDER BY number DESC
`

func (q *Queries) ListAllChanges(ctx context.Context, db DBTX, monorepoID uuid.UUID) ([]*Change, error) {
	rows, err := db.Query(ctx, listAllChanges, monorepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ChangeKey,
			&i.Number,
			&i.State,
			&i.BaseSha,
			&i.HeadSha,
			&i.GitRef,
			&i.Title,
			&i.Description,
			&i.TestPlan,
			&i.AuthoredByActorID,
			&i.DependsOnChangeID,
			&i.Mechanical,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LandedAt,
			&i.LandedSha,
			&i.LandedByActorID,
			&i.OriginWorkspace,
			&i.OriginBranch,
			&i.LandedForced,
			&i.Automerge,
			&i.AutomergeBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllChangesPage = `-- name: ListAllChangesPage :many
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE monorepo_id = $1
ORDER BY number DESC
LIMIT NULLIF($3::int, 0) OFFSET $2::int
`

type ListAllChangesPageParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

func (q *Queries) ListAllChangesPage(ctx context.Context, db DBTX, arg ListAllChangesPageParams) ([]*Change, error) {
	rows, err := db.Query(ctx, listAllChangesPage, arg.MonorepoID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ChangeKey,
			&i.Number,
			&i.State,
			&i.BaseSha,
			&i.HeadSha,
			&i.GitRef,
			&i.Title,
			&i.Description,
			&i.TestPlan,
			&i.AuthoredByActorID,
			&i.DependsOnChangeID,
			&i.Mechanical,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LandedAt,
			&i.LandedSha,
			&i.LandedByActorID,
			&i.OriginWorkspace,
			&i.OriginBranch,
			&i.LandedForced,
			&i.Automerge,
			&i.AutomergeBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeAffectedProjects = `-- name: ListChangeAffectedProjects :many
SELECT p.id, p.monorepo_id, p.name, p.path, p.project_type, p.template_id, p.visibility, p.capabilities, p.declared_dependencies, p.indexed_at_sha, p.created_at, p.updated_at FROM change_affected_projects cap
JOIN projects p ON p.id = cap.project_id
WHERE cap.change_affected_id = $1
`

func (q *Queries) ListChangeAffectedProjects(ctx context.Context, db DBTX, changeAffectedID uuid.UUID) ([]*Project, error) {
	rows, err := db.Query(ctx, listChangeAffectedProjects, changeAffectedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.Name,
			&i.Path,
			&i.ProjectType,
			&i.TemplateID,
			&i.Visibility,
			&i.Capabilities,
			&i.DeclaredDependencies,
			&i.IndexedAtSha,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeAssistedBy = `-- name: ListChangeAssistedBy :many
SELECT a.id, a.org_id, a.type, a.external_ref, a.display_name, a.agent_policy_id, a.metadata, a.created_at FROM change_assisted_by cab
JOIN actors a ON a.id = cab.actor_id
WHERE cab.change_id = $1
`

func (q *Queries) ListChangeAssistedBy(ctx context.Context, db DBTX, changeID uuid.UUID) ([]*Actor, error) {
	rows, err := db.Query(ctx, listChangeAssistedBy, changeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Actor
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.ExternalRef,
			&i.DisplayName,
			&i.AgentPolicyID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeComments = `-- name: ListChangeComments :many
SELECT id, change_id, author_actor_id, body, path, line, created_at, head_sha, side, parent_id, resolved FROM change_comments WHERE change_id = $1 ORDER BY created_at LIMIT $2 OFFSET $3
`

type ListChangeCommentsParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListChangeComments(ctx context.Context, db DBTX, arg ListChangeCommentsParams) ([]*ChangeComment, error) {
	rows, err := db.Query(ctx, listChangeComments, arg.ChangeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChangeComment
	for rows.Next() {
		var i ChangeComment
		if err := rows.Scan(
			&i.ID,
			&i.ChangeID,
			&i.AuthorActorID,
			&i.Body,
			&i.Path,
			&i.Line,
			&i.CreatedAt,
			&i.HeadSha,
			&i.Side,
			&i.ParentID,
			&i.Resolved,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeOwnerRequirements = `-- name: ListChangeOwnerRequirements :many
SELECT change_id, owner_ref, satisfied, satisfied_by_actor_id, satisfied_at, satisfied_for_head_sha FROM change_owner_requirements WHERE change_id = $1
`

func (q *Queries) ListChangeOwnerRequirements(ctx context.Context, db DBTX, changeID uuid.UUID) ([]*ChangeOwnerRequirement, error) {
	rows, err := db.Query(ctx, listChangeOwnerRequirements, changeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChangeOwnerRequirement
	for rows.Next() {
		var i ChangeOwnerRequirement
		if err := rows.Scan(
			&i.ChangeID,
			&i.OwnerRef,
			&i.Satisfied,
			&i.SatisfiedByActorID,
			&i.SatisfiedAt,
			&i.SatisfiedForHeadSha,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeReviewRequests = `-- name: ListChangeReviewRequests :many
SELECT change_id, reviewer, requested_by, created_at FROM change_review_requests WHERE change_id = $1 ORDER BY reviewer
`

func (q *Queries) ListChangeReviewRequests(ctx context.Context, db DBTX, changeID uuid.UUID) ([]*ChangeReviewRequest, error) {
	rows, err := db.Query(ctx, listChangeReviewRequests, changeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChangeReviewRequest
	for rows.Next() {
		var i ChangeReviewRequest
		if err := rows.Scan(
			&i.ChangeID,
			&i.Reviewer,
			&i.RequestedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangesByState = `-- name: ListChangesByState :many
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE monorepo_id = $1 AND state = $2 ORDER BY number DESC
`

type ListChangesByStateParams struct {
	MonorepoID uuid.UUID   `json:"monorepo_id"`
	State      ChangeState `json:"state"`
}

func (q *Queries) ListChangesByState(ctx context.Context, db DBTX, arg ListChangesByStateParams) ([]*Change, error) {
	rows, err := db.Query(ctx, listChangesByState, arg.MonorepoID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ChangeKey,
			&i.Number,
			&i.State,
			&i.BaseSha,
			&i.HeadSha,
			&i.GitRef,
			&i.Title,
			&i.Description,
			&i.TestPlan,
			&i.AuthoredByActorID,
			&i.DependsOnChangeID,
			&i.Mechanical,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LandedAt,
			&i.LandedSha,
			&i.LandedByActorID,
			&i.OriginWorkspace,
			&i.OriginBranch,
			&i.LandedForced,
			&i.Automerge,
			&i.AutomergeBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangesByStatePage = `-- name: ListChangesByStatePage :many
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE monorepo_id = $1 AND state = $2
ORDER BY number DESC
LIMIT NULLIF($4::int, 0) OFFSET $3::int
`

type ListChangesByStatePageParams struct {
	MonorepoID uuid.UUID   `json:"monorepo_id"`
	State      ChangeState `json:"state"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

// One page of ListChangesByState, newest first - LIMIT/OFFSET ride
// idx_changes_state_number (migration 0010). page_limit 0 means no limit
// (NULLIF turns it into LIMIT NULL), matching Store.ListChangesPage's
// contract.
func (q *Queries) ListChangesByStatePage(ctx context.Context, db DBTX, arg ListChangesByStatePageParams) ([]*Change, error) {
	rows, err := db.Query(ctx, listChangesByStatePage,
		arg.MonorepoID,
		arg.State,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ChangeKey,
			&i.Number,
			&i.State,
			&i.BaseSha,
			&i.HeadSha,
			&i.GitRef,
			&i.Title,
			&i.Description,
			&i.TestPlan,
			&i.AuthoredByActorID,
			&i.DependsOnChangeID,
			&i.Mechanical,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LandedAt,
			&i.LandedSha,
			&i.LandedByActorID,
			&i.OriginWorkspace,
			&i.OriginBranch,
			&i.LandedForced,
			&i.Automerge,
			&i.AutomergeBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLandedChanges = `-- name: ListLandedChanges :many
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE monorepo_id = $1 AND state = 'landed'
ORDER BY landed_at DESC, number DESC
`

// Landed listings read in LANDING order, not creation order (finding #45):
// number is assigned at creation, so a later-created change that landed
// first would sort above the change that landed after it. landed_at is the
// one clock that matches trunk order (finding #43); number breaks the
// (sub-microsecond) ties deterministically. Rides idx_changes_landed_order
// (migration 0018) - the state literal is what lets the planner use the
// partial index.
func (q *Queries) ListLandedChanges(ctx context.Context, db DBTX, monorepoID uuid.UUID) ([]*Change, error) {
	rows, err := db.Query(ctx, listLandedChanges, monorepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ChangeKey,
			&i.Number,
			&i.State,
			&i.BaseSha,
			&i.HeadSha,
			&i.GitRef,
			&i.Title,
			&i.Description,
			&i.TestPlan,
			&i.AuthoredByActorID,
			&i.DependsOnChangeID,
			&i.Mechanical,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LandedAt,
			&i.LandedSha,
			&i.LandedByActorID,
			&i.OriginWorkspace,
			&i.OriginBranch,
			&i.LandedForced,
			&i.Automerge,
			&i.AutomergeBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLandedChangesPage = `-- name: ListLandedChangesPage :many
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE monorepo_id = $1 AND state = 'landed'
ORDER BY landed_at DESC, number DESC
LIMIT NULLIF($3::int, 0) OFFSET $2::int
`

type ListLandedChangesPageParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

// One page of ListLandedChanges - same LIMIT NULLIF(x, 0) contract as
// ListChangesByStatePage.
func (q *Queries) ListLandedChangesPage(ctx context.Context, db DBTX, arg ListLandedChangesPageParams) ([]*Change, error) {
	rows, err := db.Query(ctx, listLandedChangesPage, arg.MonorepoID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ChangeKey,
			&i.Number,
			&i.State,
			&i.BaseSha,
			&i.HeadSha,
			&i.GitRef,
			&i.Title,
			&i.Description,
			&i.TestPlan,
			&i.AuthoredByActorID,
			&i.DependsOnChangeID,
			&i.Mechanical,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LandedAt,
			&i.LandedSha,
			&i.LandedByActorID,
			&i.OriginWorkspace,
			&i.OriginBranch,
			&i.LandedForced,
			&i.Automerge,
			&i.AutomergeBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenChanges = `-- name: ListOpenChanges :many
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by FROM changes WHERE monorepo_id = $1 AND state = 'open' ORDER BY number DESC LIMIT $2 OFFSET $3
`

type ListOpenChangesParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListOpenChanges(ctx context.Context, db DBTX, arg ListOpenChangesParams) ([]*Change, error) {
	rows, err := db.Query(ctx, listOpenChanges, arg.MonorepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ChangeKey,
			&i.Number,
			&i.State,
			&i.BaseSha,
			&i.HeadSha,
			&i.GitRef,
			&i.Title,
			&i.Description,
			&i.TestPlan,
			&i.AuthoredByActorID,
			&i.DependsOnChangeID,
			&i.Mechanical,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LandedAt,
			&i.LandedSha,
			&i.LandedByActorID,
			&i.OriginWorkspace,
			&i.OriginBranch,
			&i.LandedForced,
			&i.Automerge,
			&i.AutomergeBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChangeComment = `-- name: ResolveChangeComment :execrows
UPDATE change_comments SET resolved = $3 WHERE id = $1 AND change_id = $2
`

type ResolveChangeCommentParams struct {
	ID       uuid.UUID `json:"id"`
	ChangeID uuid.UUID `json:"change_id"`
	Resolved bool      `json:"resolved"`
}

func (q *Queries) ResolveChangeComment(ctx context.Context, db DBTX, arg ResolveChangeCommentParams) (int64, error) {
	result, err := db.Exec(ctx, resolveChangeComment, arg.ID, arg.ChangeID, arg.Resolved)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const satisfyChangeOwnerRequirement = `-- name: SatisfyChangeOwnerRequirement :exec
UPDATE change_owner_requirements
SET satisfied = true, satisfied_by_actor_id = $3, satisfied_at = now(),
    satisfied_for_head_sha = $4
WHERE change_id = $1 AND owner_ref = $2
`

type SatisfyChangeOwnerRequirementParams struct {
	ChangeID            uuid.UUID   `json:"change_id"`
	OwnerRef            string      `json:"owner_ref"`
	SatisfiedByActorID  pgtype.UUID `json:"satisfied_by_actor_id"`
	SatisfiedForHeadSha *string     `json:"satisfied_for_head_sha"`
}

func (q *Queries) SatisfyChangeOwnerRequirement(ctx context.Context, db DBTX, arg SatisfyChangeOwnerRequirementParams) error {
	_, err := db.Exec(ctx, satisfyChangeOwnerRequirement,
		arg.ChangeID,
		arg.OwnerRef,
		arg.SatisfiedByActorID,
		arg.SatisfiedForHeadSha,
	)
	return err
}

const setChangeAutomerge = `-- name: SetChangeAutomerge :one
UPDATE changes SET automerge = $2,
    automerge_by = CASE WHEN $2 THEN $3::text ELSE '' END,
    updated_at = now()
WHERE id = $1 RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by
`

type SetChangeAutomergeParams struct {
	ID          uuid.UUID `json:"id"`
	Automerge   bool      `json:"automerge"`
	AutomergeBy string    `json:"automerge_by"`
}

// Arm/disarm the when-ready land (§13.5). Disarming clears the armer.
func (q *Queries) SetChangeAutomerge(ctx context.Context, db DBTX, arg SetChangeAutomergeParams) (*Change, error) {
	row := db.QueryRow(ctx, setChangeAutomerge, arg.ID, arg.Automerge, arg.AutomergeBy)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
		&i.LandedByActorID,
		&i.OriginWorkspace,
		&i.OriginBranch,
		&i.LandedForced,
		&i.Automerge,
		&i.AutomergeBy,
	)
	return &i, err
}

const setChangeOwnerRequirement = `-- name: SetChangeOwnerRequirement :exec
INSERT INTO change_owner_requirements (change_id, owner_ref, satisfied)
VALUES ($1, $2, false)
ON CONFLICT (change_id, owner_ref) DO NOTHING
`

type SetChangeOwnerRequirementParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	OwnerRef string    `json:"owner_ref"`
}

func (q *Queries) SetChangeOwnerRequirement(ctx context.Context, db DBTX, arg SetChangeOwnerRequirementParams) error {
	_, err := db.Exec(ctx, setChangeOwnerRequirement, arg.ChangeID, arg.OwnerRef)
	return err
}

const updateChangeDescription = `-- name: UpdateChangeDescription :one
UPDATE changes SET description = $2, test_plan = $3, updated_at = now() WHERE id = $1 RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by
`

type UpdateChangeDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	TestPlan    string    `json:"test_plan"`
}

func (q *Queries) UpdateChangeDescription(ctx context.Context, db DBTX, arg UpdateChangeDescriptionParams) (*Change, error) {
	row := db.QueryRow(ctx, updateChangeDescription, arg.ID, arg.Description, arg.TestPlan)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
		&i.LandedByActorID,
		&i.OriginWorkspace,
		&i.OriginBranch,
		&i.LandedForced,
		&i.Automerge,
		&i.AutomergeBy,
	)
	return &i, err
}

const updateChangeHead = `-- name: UpdateChangeHead :one
UPDATE changes SET head_sha = $2, git_ref = $3, authored_by_actor_id = $4, base_sha = $5,
    title = $6::text,
    origin_workspace = CASE WHEN $7::text = '' THEN changes.origin_workspace ELSE $7::text END,
    origin_branch = CASE WHEN $7::text = '' THEN changes.origin_branch ELSE $8::text END,
    state = CASE WHEN changes.state = 'abandoned' THEN 'open'::change_state ELSE changes.state END,
    updated_at = now()
WHERE id = $1 RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha, landed_by_actor_id, origin_workspace, origin_branch, landed_forced, automerge, automerge_by
`

type UpdateChangeHeadParams struct {
	ID                uuid.UUID `json:"id"`
	HeadSha           string    `json:"head_sha"`
	GitRef            string    `json:"git_ref"`
	AuthoredByActorID uuid.UUID `json:"authored_by_actor_id"`
	BaseSha           string    `json:"base_sha"`
	Title             string    `json:"title"`
	OriginWorkspace   string    `json:"origin_workspace"`
	OriginBranch      string    `json:"origin_branch"`
}

// authored_by_actor_id moves with the head: the last pusher owns the
// current content, which is also who self-approval is checked against
// (§8.7, stage 12c). base_sha moves with it too (compose edge case E7):
// it is merge-base(head, trunk) at push time, and freezing the creation-
// time value made §13.5's requires_revalidation a permanent dead end.
// Re-pushing an abandoned Change reopens it (§7.4 - the change.reopened
// webhook event modeled this from day one); landed stays landed, it is
// terminal. Origin provenance (§12.2 branch ↔ stack) moves with the head
// when the push carries it, and is PRESERVED when it doesn't - a plain-git
// amend of a workspace Change must not erase where the Change lives.
// Title moves with the head too: an amend that rewords the commit subject
// is the pusher renaming the Change.
func (q *Queries) UpdateChangeHead(ctx context.Context, db DBTX, arg UpdateChangeHeadParams) (*Change, error) {
	row := db.QueryRow(ctx, updateChangeHead,
		arg.ID,
		arg.HeadSha,
		arg.GitRef,
		arg.AuthoredByActorID,
		arg.BaseSha,
		arg.Title,
		arg.OriginWorkspace,
		arg.OriginBranch,
	)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
		&i.LandedByActorID,
		&i.OriginWorkspace,
		&i.OriginBranch,
		&i.LandedForced,
		&i.Automerge,
		&i.AutomergeBy,
	)
	return &i, err
}

const upsertChangeAffected = `-- name: UpsertChangeAffected :one
INSERT INTO change_affected (change_id, head_sha, computation_id, run_everything, reason_codes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (change_id, head_sha) DO UPDATE
    SET computation_id = EXCLUDED.computation_id,
        run_everything = EXCLUDED.run_everything,
        reason_codes = EXCLUDED.reason_codes
RETURNING id, change_id, head_sha, computation_id, run_everything, reason_codes, computed_at
`

type UpsertChangeAffectedParams struct {
	ChangeID      uuid.UUID `json:"change_id"`
	HeadSha       string    `json:"head_sha"`
	ComputationID string    `json:"computation_id"`
	RunEverything bool      `json:"run_everything"`
	ReasonCodes   []string  `json:"reason_codes"`
}

func (q *Queries) UpsertChangeAffected(ctx context.Context, db DBTX, arg UpsertChangeAffectedParams) (*ChangeAffected, error) {
	row := db.QueryRow(ctx, upsertChangeAffected,
		arg.ChangeID,
		arg.HeadSha,
		arg.ComputationID,
		arg.RunEverything,
		arg.ReasonCodes,
	)
	var i ChangeAffected
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.HeadSha,
		&i.ComputationID,
		&i.RunEverything,
		&i.ReasonCodes,
		&i.ComputedAt,
	)
	return &i, err
}

const upsertChangeReviewRequest = `-- name: UpsertChangeReviewRequest :exec
INSERT INTO change_review_requests (change_id, reviewer, requested_by)
VALUES ($1, $2, $3)
ON CONFLICT (change_id, reviewer) DO UPDATE SET requested_by = EXCLUDED.requested_by
`

type UpsertChangeReviewRequestParams struct {
	ChangeID    uuid.UUID `json:"change_id"`
	Reviewer    string    `json:"reviewer"`
	RequestedBy string    `json:"requested_by"`
}

func (q *Queries) UpsertChangeReviewRequest(ctx context.Context, db DBTX, arg UpsertChangeReviewRequestParams) error {
	_, err := db.Exec(ctx, upsertChangeReviewRequest, arg.ChangeID, arg.Reviewer, arg.RequestedBy)
	return err
}
