// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changes.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addChangeAffectedProject = `-- name: AddChangeAffectedProject :exec
INSERT INTO change_affected_projects (change_affected_id, project_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddChangeAffectedProjectParams struct {
	ChangeAffectedID uuid.UUID `json:"change_affected_id"`
	ProjectID        uuid.UUID `json:"project_id"`
}

func (q *Queries) AddChangeAffectedProject(ctx context.Context, db DBTX, arg AddChangeAffectedProjectParams) error {
	_, err := db.Exec(ctx, addChangeAffectedProject, arg.ChangeAffectedID, arg.ProjectID)
	return err
}

const addChangeAssistedBy = `-- name: AddChangeAssistedBy :exec
INSERT INTO change_assisted_by (change_id, actor_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddChangeAssistedByParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	ActorID  uuid.UUID `json:"actor_id"`
}

func (q *Queries) AddChangeAssistedBy(ctx context.Context, db DBTX, arg AddChangeAssistedByParams) error {
	_, err := db.Exec(ctx, addChangeAssistedBy, arg.ChangeID, arg.ActorID)
	return err
}

const createChange = `-- name: CreateChange :one
INSERT INTO changes (
    monorepo_id, change_key, state, base_sha, head_sha, git_ref, title,
    description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha
`

type CreateChangeParams struct {
	MonorepoID        uuid.UUID   `json:"monorepo_id"`
	ChangeKey         string      `json:"change_key"`
	State             ChangeState `json:"state"`
	BaseSha           string      `json:"base_sha"`
	HeadSha           string      `json:"head_sha"`
	GitRef            string      `json:"git_ref"`
	Title             string      `json:"title"`
	Description       string      `json:"description"`
	TestPlan          string      `json:"test_plan"`
	AuthoredByActorID uuid.UUID   `json:"authored_by_actor_id"`
	DependsOnChangeID pgtype.UUID `json:"depends_on_change_id"`
	Mechanical        bool        `json:"mechanical"`
}

func (q *Queries) CreateChange(ctx context.Context, db DBTX, arg CreateChangeParams) (*Change, error) {
	row := db.QueryRow(ctx, createChange,
		arg.MonorepoID,
		arg.ChangeKey,
		arg.State,
		arg.BaseSha,
		arg.HeadSha,
		arg.GitRef,
		arg.Title,
		arg.Description,
		arg.TestPlan,
		arg.AuthoredByActorID,
		arg.DependsOnChangeID,
		arg.Mechanical,
	)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
	)
	return &i, err
}

const createChangeComment = `-- name: CreateChangeComment :one
INSERT INTO change_comments (change_id, author_actor_id, body, path, line)
VALUES ($1, $2, $3, $4, $5) RETURNING id, change_id, author_actor_id, body, path, line, created_at
`

type CreateChangeCommentParams struct {
	ChangeID      uuid.UUID `json:"change_id"`
	AuthorActorID uuid.UUID `json:"author_actor_id"`
	Body          string    `json:"body"`
	Path          *string   `json:"path"`
	Line          *int32    `json:"line"`
}

func (q *Queries) CreateChangeComment(ctx context.Context, db DBTX, arg CreateChangeCommentParams) (*ChangeComment, error) {
	row := db.QueryRow(ctx, createChangeComment,
		arg.ChangeID,
		arg.AuthorActorID,
		arg.Body,
		arg.Path,
		arg.Line,
	)
	var i ChangeComment
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.AuthorActorID,
		&i.Body,
		&i.Path,
		&i.Line,
		&i.CreatedAt,
	)
	return &i, err
}

const getChange = `-- name: GetChange :one
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha FROM changes WHERE id = $1
`

func (q *Queries) GetChange(ctx context.Context, db DBTX, id uuid.UUID) (*Change, error) {
	row := db.QueryRow(ctx, getChange, id)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
	)
	return &i, err
}

const getChangeAffected = `-- name: GetChangeAffected :one
SELECT id, change_id, head_sha, computation_id, run_everything, reason_codes, computed_at FROM change_affected WHERE change_id = $1 AND head_sha = $2
`

type GetChangeAffectedParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	HeadSha  string    `json:"head_sha"`
}

func (q *Queries) GetChangeAffected(ctx context.Context, db DBTX, arg GetChangeAffectedParams) (*ChangeAffected, error) {
	row := db.QueryRow(ctx, getChangeAffected, arg.ChangeID, arg.HeadSha)
	var i ChangeAffected
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.HeadSha,
		&i.ComputationID,
		&i.RunEverything,
		&i.ReasonCodes,
		&i.ComputedAt,
	)
	return &i, err
}

const getChangeByKey = `-- name: GetChangeByKey :one
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha FROM changes WHERE monorepo_id = $1 AND change_key = $2
`

type GetChangeByKeyParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	ChangeKey  string    `json:"change_key"`
}

func (q *Queries) GetChangeByKey(ctx context.Context, db DBTX, arg GetChangeByKeyParams) (*Change, error) {
	row := db.QueryRow(ctx, getChangeByKey, arg.MonorepoID, arg.ChangeKey)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
	)
	return &i, err
}

const landChange = `-- name: LandChange :one
UPDATE changes SET state = 'landed', landed_at = now(), landed_sha = $2, updated_at = now() WHERE id = $1 RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha
`

type LandChangeParams struct {
	ID        uuid.UUID `json:"id"`
	LandedSha *string   `json:"landed_sha"`
}

func (q *Queries) LandChange(ctx context.Context, db DBTX, arg LandChangeParams) (*Change, error) {
	row := db.QueryRow(ctx, landChange, arg.ID, arg.LandedSha)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
	)
	return &i, err
}

const listChangeAffectedProjects = `-- name: ListChangeAffectedProjects :many
SELECT p.id, p.monorepo_id, p.name, p.path, p.project_type, p.template_id, p.visibility, p.capabilities, p.declared_dependencies, p.indexed_at_sha, p.created_at, p.updated_at FROM change_affected_projects cap
JOIN projects p ON p.id = cap.project_id
WHERE cap.change_affected_id = $1
`

func (q *Queries) ListChangeAffectedProjects(ctx context.Context, db DBTX, changeAffectedID uuid.UUID) ([]*Project, error) {
	rows, err := db.Query(ctx, listChangeAffectedProjects, changeAffectedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.Name,
			&i.Path,
			&i.ProjectType,
			&i.TemplateID,
			&i.Visibility,
			&i.Capabilities,
			&i.DeclaredDependencies,
			&i.IndexedAtSha,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeAssistedBy = `-- name: ListChangeAssistedBy :many
SELECT a.id, a.org_id, a.type, a.external_ref, a.display_name, a.agent_policy_id, a.metadata, a.created_at FROM change_assisted_by cab
JOIN actors a ON a.id = cab.actor_id
WHERE cab.change_id = $1
`

func (q *Queries) ListChangeAssistedBy(ctx context.Context, db DBTX, changeID uuid.UUID) ([]*Actor, error) {
	rows, err := db.Query(ctx, listChangeAssistedBy, changeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Actor
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.ExternalRef,
			&i.DisplayName,
			&i.AgentPolicyID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeComments = `-- name: ListChangeComments :many
SELECT id, change_id, author_actor_id, body, path, line, created_at FROM change_comments WHERE change_id = $1 ORDER BY created_at LIMIT $2 OFFSET $3
`

type ListChangeCommentsParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListChangeComments(ctx context.Context, db DBTX, arg ListChangeCommentsParams) ([]*ChangeComment, error) {
	rows, err := db.Query(ctx, listChangeComments, arg.ChangeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChangeComment
	for rows.Next() {
		var i ChangeComment
		if err := rows.Scan(
			&i.ID,
			&i.ChangeID,
			&i.AuthorActorID,
			&i.Body,
			&i.Path,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeOwnerRequirements = `-- name: ListChangeOwnerRequirements :many
SELECT change_id, owner_ref, satisfied, satisfied_by_actor_id, satisfied_at FROM change_owner_requirements WHERE change_id = $1
`

func (q *Queries) ListChangeOwnerRequirements(ctx context.Context, db DBTX, changeID uuid.UUID) ([]*ChangeOwnerRequirement, error) {
	rows, err := db.Query(ctx, listChangeOwnerRequirements, changeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChangeOwnerRequirement
	for rows.Next() {
		var i ChangeOwnerRequirement
		if err := rows.Scan(
			&i.ChangeID,
			&i.OwnerRef,
			&i.Satisfied,
			&i.SatisfiedByActorID,
			&i.SatisfiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenChanges = `-- name: ListOpenChanges :many
SELECT id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha FROM changes WHERE monorepo_id = $1 AND state = 'open' ORDER BY number DESC LIMIT $2 OFFSET $3
`

type ListOpenChangesParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListOpenChanges(ctx context.Context, db DBTX, arg ListOpenChangesParams) ([]*Change, error) {
	rows, err := db.Query(ctx, listOpenChanges, arg.MonorepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ChangeKey,
			&i.Number,
			&i.State,
			&i.BaseSha,
			&i.HeadSha,
			&i.GitRef,
			&i.Title,
			&i.Description,
			&i.TestPlan,
			&i.AuthoredByActorID,
			&i.DependsOnChangeID,
			&i.Mechanical,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LandedAt,
			&i.LandedSha,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const satisfyChangeOwnerRequirement = `-- name: SatisfyChangeOwnerRequirement :exec
UPDATE change_owner_requirements
SET satisfied = true, satisfied_by_actor_id = $3, satisfied_at = now()
WHERE change_id = $1 AND owner_ref = $2
`

type SatisfyChangeOwnerRequirementParams struct {
	ChangeID           uuid.UUID   `json:"change_id"`
	OwnerRef           string      `json:"owner_ref"`
	SatisfiedByActorID pgtype.UUID `json:"satisfied_by_actor_id"`
}

func (q *Queries) SatisfyChangeOwnerRequirement(ctx context.Context, db DBTX, arg SatisfyChangeOwnerRequirementParams) error {
	_, err := db.Exec(ctx, satisfyChangeOwnerRequirement, arg.ChangeID, arg.OwnerRef, arg.SatisfiedByActorID)
	return err
}

const setChangeOwnerRequirement = `-- name: SetChangeOwnerRequirement :exec
INSERT INTO change_owner_requirements (change_id, owner_ref, satisfied)
VALUES ($1, $2, false)
ON CONFLICT (change_id, owner_ref) DO NOTHING
`

type SetChangeOwnerRequirementParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	OwnerRef string    `json:"owner_ref"`
}

func (q *Queries) SetChangeOwnerRequirement(ctx context.Context, db DBTX, arg SetChangeOwnerRequirementParams) error {
	_, err := db.Exec(ctx, setChangeOwnerRequirement, arg.ChangeID, arg.OwnerRef)
	return err
}

const updateChangeDescription = `-- name: UpdateChangeDescription :one
UPDATE changes SET description = $2, test_plan = $3, updated_at = now() WHERE id = $1 RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha
`

type UpdateChangeDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	TestPlan    string    `json:"test_plan"`
}

func (q *Queries) UpdateChangeDescription(ctx context.Context, db DBTX, arg UpdateChangeDescriptionParams) (*Change, error) {
	row := db.QueryRow(ctx, updateChangeDescription, arg.ID, arg.Description, arg.TestPlan)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
	)
	return &i, err
}

const updateChangeHead = `-- name: UpdateChangeHead :one
UPDATE changes SET head_sha = $2, git_ref = $3, updated_at = now() WHERE id = $1 RETURNING id, monorepo_id, change_key, number, state, base_sha, head_sha, git_ref, title, description, test_plan, authored_by_actor_id, depends_on_change_id, mechanical, created_at, updated_at, landed_at, landed_sha
`

type UpdateChangeHeadParams struct {
	ID      uuid.UUID `json:"id"`
	HeadSha string    `json:"head_sha"`
	GitRef  string    `json:"git_ref"`
}

func (q *Queries) UpdateChangeHead(ctx context.Context, db DBTX, arg UpdateChangeHeadParams) (*Change, error) {
	row := db.QueryRow(ctx, updateChangeHead, arg.ID, arg.HeadSha, arg.GitRef)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ChangeKey,
		&i.Number,
		&i.State,
		&i.BaseSha,
		&i.HeadSha,
		&i.GitRef,
		&i.Title,
		&i.Description,
		&i.TestPlan,
		&i.AuthoredByActorID,
		&i.DependsOnChangeID,
		&i.Mechanical,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LandedAt,
		&i.LandedSha,
	)
	return &i, err
}

const upsertChangeAffected = `-- name: UpsertChangeAffected :one
INSERT INTO change_affected (change_id, head_sha, computation_id, run_everything, reason_codes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (change_id, head_sha) DO UPDATE
    SET computation_id = EXCLUDED.computation_id,
        run_everything = EXCLUDED.run_everything,
        reason_codes = EXCLUDED.reason_codes
RETURNING id, change_id, head_sha, computation_id, run_everything, reason_codes, computed_at
`

type UpsertChangeAffectedParams struct {
	ChangeID      uuid.UUID `json:"change_id"`
	HeadSha       string    `json:"head_sha"`
	ComputationID string    `json:"computation_id"`
	RunEverything bool      `json:"run_everything"`
	ReasonCodes   []string  `json:"reason_codes"`
}

func (q *Queries) UpsertChangeAffected(ctx context.Context, db DBTX, arg UpsertChangeAffectedParams) (*ChangeAffected, error) {
	row := db.QueryRow(ctx, upsertChangeAffected,
		arg.ChangeID,
		arg.HeadSha,
		arg.ComputationID,
		arg.RunEverything,
		arg.ReasonCodes,
	)
	var i ChangeAffected
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.HeadSha,
		&i.ComputationID,
		&i.RunEverything,
		&i.ReasonCodes,
		&i.ComputedAt,
	)
	return &i, err
}
