// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCheckAnnotation = `-- name: AddCheckAnnotation :one
INSERT INTO check_annotations (check_run_id, path, start_line, end_line, annotation_level, message, title)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, check_run_id, path, start_line, end_line, annotation_level, message, title
`

type AddCheckAnnotationParams struct {
	CheckRunID      uuid.UUID `json:"check_run_id"`
	Path            string    `json:"path"`
	StartLine       int32     `json:"start_line"`
	EndLine         int32     `json:"end_line"`
	AnnotationLevel string    `json:"annotation_level"`
	Message         string    `json:"message"`
	Title           *string   `json:"title"`
}

func (q *Queries) AddCheckAnnotation(ctx context.Context, db DBTX, arg AddCheckAnnotationParams) (*CheckAnnotation, error) {
	row := db.QueryRow(ctx, addCheckAnnotation,
		arg.CheckRunID,
		arg.Path,
		arg.StartLine,
		arg.EndLine,
		arg.AnnotationLevel,
		arg.Message,
		arg.Title,
	)
	var i CheckAnnotation
	err := row.Scan(
		&i.ID,
		&i.CheckRunID,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.AnnotationLevel,
		&i.Message,
		&i.Title,
	)
	return &i, err
}

const createCheckRun = `-- name: CreateCheckRun :one
INSERT INTO check_runs (
    change_id, head_sha, name, external_id, status, conclusion, started_at,
    details_url, output_title, output_summary, output_text, app_id, reporter,
    attempt, ttl_seconds
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, change_id, head_sha, name, external_id, status, conclusion, started_at, completed_at, details_url, output_title, output_summary, output_text, app_id, reporter, attempt, ttl_seconds, last_seen_at, created_at
`

type CreateCheckRunParams struct {
	ChangeID      uuid.UUID          `json:"change_id"`
	HeadSha       string             `json:"head_sha"`
	Name          string             `json:"name"`
	ExternalID    string             `json:"external_id"`
	Status        CheckStatus        `json:"status"`
	Conclusion    *CheckConclusion   `json:"conclusion"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	DetailsUrl    *string            `json:"details_url"`
	OutputTitle   *string            `json:"output_title"`
	OutputSummary *string            `json:"output_summary"`
	OutputText    *string            `json:"output_text"`
	AppID         *string            `json:"app_id"`
	Reporter      string             `json:"reporter"`
	Attempt       int32              `json:"attempt"`
	TtlSeconds    int32              `json:"ttl_seconds"`
}

func (q *Queries) CreateCheckRun(ctx context.Context, db DBTX, arg CreateCheckRunParams) (*CheckRun, error) {
	row := db.QueryRow(ctx, createCheckRun,
		arg.ChangeID,
		arg.HeadSha,
		arg.Name,
		arg.ExternalID,
		arg.Status,
		arg.Conclusion,
		arg.StartedAt,
		arg.DetailsUrl,
		arg.OutputTitle,
		arg.OutputSummary,
		arg.OutputText,
		arg.AppID,
		arg.Reporter,
		arg.Attempt,
		arg.TtlSeconds,
	)
	var i CheckRun
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.HeadSha,
		&i.Name,
		&i.ExternalID,
		&i.Status,
		&i.Conclusion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DetailsUrl,
		&i.OutputTitle,
		&i.OutputSummary,
		&i.OutputText,
		&i.AppID,
		&i.Reporter,
		&i.Attempt,
		&i.TtlSeconds,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getLatestCheckRunAttempt = `-- name: GetLatestCheckRunAttempt :one
SELECT id, change_id, head_sha, name, external_id, status, conclusion, started_at, completed_at, details_url, output_title, output_summary, output_text, app_id, reporter, attempt, ttl_seconds, last_seen_at, created_at FROM check_runs
WHERE change_id = $1 AND head_sha = $2 AND name = $3
ORDER BY attempt DESC LIMIT 1
`

type GetLatestCheckRunAttemptParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	HeadSha  string    `json:"head_sha"`
	Name     string    `json:"name"`
}

func (q *Queries) GetLatestCheckRunAttempt(ctx context.Context, db DBTX, arg GetLatestCheckRunAttemptParams) (*CheckRun, error) {
	row := db.QueryRow(ctx, getLatestCheckRunAttempt, arg.ChangeID, arg.HeadSha, arg.Name)
	var i CheckRun
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.HeadSha,
		&i.Name,
		&i.ExternalID,
		&i.Status,
		&i.Conclusion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DetailsUrl,
		&i.OutputTitle,
		&i.OutputSummary,
		&i.OutputText,
		&i.AppID,
		&i.Reporter,
		&i.Attempt,
		&i.TtlSeconds,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listCheckAnnotations = `-- name: ListCheckAnnotations :many
SELECT id, check_run_id, path, start_line, end_line, annotation_level, message, title FROM check_annotations WHERE check_run_id = $1
`

func (q *Queries) ListCheckAnnotations(ctx context.Context, db DBTX, checkRunID uuid.UUID) ([]*CheckAnnotation, error) {
	rows, err := db.Query(ctx, listCheckAnnotations, checkRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CheckAnnotation
	for rows.Next() {
		var i CheckAnnotation
		if err := rows.Scan(
			&i.ID,
			&i.CheckRunID,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.AnnotationLevel,
			&i.Message,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckRunsForChange = `-- name: ListCheckRunsForChange :many
SELECT id, change_id, head_sha, name, external_id, status, conclusion, started_at, completed_at, details_url, output_title, output_summary, output_text, app_id, reporter, attempt, ttl_seconds, last_seen_at, created_at FROM check_runs WHERE change_id = $1 AND head_sha = $2 ORDER BY name, attempt
`

type ListCheckRunsForChangeParams struct {
	ChangeID uuid.UUID `json:"change_id"`
	HeadSha  string    `json:"head_sha"`
}

func (q *Queries) ListCheckRunsForChange(ctx context.Context, db DBTX, arg ListCheckRunsForChangeParams) ([]*CheckRun, error) {
	rows, err := db.Query(ctx, listCheckRunsForChange, arg.ChangeID, arg.HeadSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CheckRun
	for rows.Next() {
		var i CheckRun
		if err := rows.Scan(
			&i.ID,
			&i.ChangeID,
			&i.HeadSha,
			&i.Name,
			&i.ExternalID,
			&i.Status,
			&i.Conclusion,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DetailsUrl,
			&i.OutputTitle,
			&i.OutputSummary,
			&i.OutputText,
			&i.AppID,
			&i.Reporter,
			&i.Attempt,
			&i.TtlSeconds,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleCheckRuns = `-- name: ListStaleCheckRuns :many
SELECT id, change_id, head_sha, name, external_id, status, conclusion, started_at, completed_at, details_url, output_title, output_summary, output_text, app_id, reporter, attempt, ttl_seconds, last_seen_at, created_at FROM check_runs
WHERE status IN ('queued', 'in_progress')
  AND last_seen_at < now() - make_interval(secs => ttl_seconds)
`

func (q *Queries) ListStaleCheckRuns(ctx context.Context, db DBTX) ([]*CheckRun, error) {
	rows, err := db.Query(ctx, listStaleCheckRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CheckRun
	for rows.Next() {
		var i CheckRun
		if err := rows.Scan(
			&i.ID,
			&i.ChangeID,
			&i.HeadSha,
			&i.Name,
			&i.ExternalID,
			&i.Status,
			&i.Conclusion,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DetailsUrl,
			&i.OutputTitle,
			&i.OutputSummary,
			&i.OutputText,
			&i.AppID,
			&i.Reporter,
			&i.Attempt,
			&i.TtlSeconds,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckRun = `-- name: UpdateCheckRun :one
UPDATE check_runs
SET status = $2, conclusion = $3, completed_at = $4, details_url = $5,
    output_title = $6, output_summary = $7, output_text = $8, last_seen_at = now()
WHERE id = $1
RETURNING id, change_id, head_sha, name, external_id, status, conclusion, started_at, completed_at, details_url, output_title, output_summary, output_text, app_id, reporter, attempt, ttl_seconds, last_seen_at, created_at
`

type UpdateCheckRunParams struct {
	ID            uuid.UUID          `json:"id"`
	Status        CheckStatus        `json:"status"`
	Conclusion    *CheckConclusion   `json:"conclusion"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DetailsUrl    *string            `json:"details_url"`
	OutputTitle   *string            `json:"output_title"`
	OutputSummary *string            `json:"output_summary"`
	OutputText    *string            `json:"output_text"`
}

func (q *Queries) UpdateCheckRun(ctx context.Context, db DBTX, arg UpdateCheckRunParams) (*CheckRun, error) {
	row := db.QueryRow(ctx, updateCheckRun,
		arg.ID,
		arg.Status,
		arg.Conclusion,
		arg.CompletedAt,
		arg.DetailsUrl,
		arg.OutputTitle,
		arg.OutputSummary,
		arg.OutputText,
	)
	var i CheckRun
	err := row.Scan(
		&i.ID,
		&i.ChangeID,
		&i.HeadSha,
		&i.Name,
		&i.ExternalID,
		&i.Status,
		&i.Conclusion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DetailsUrl,
		&i.OutputTitle,
		&i.OutputSummary,
		&i.OutputText,
		&i.AppID,
		&i.Reporter,
		&i.Attempt,
		&i.TtlSeconds,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return &i, err
}
