// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploys.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDeployRecord = `-- name: GetDeployRecord :one
SELECT monorepo_id, trunk_sha, change_key, expected, state, provenance, created_at, ready_at FROM deploy_records WHERE monorepo_id = $1 AND trunk_sha = $2
`

type GetDeployRecordParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	TrunkSha   string    `json:"trunk_sha"`
}

func (q *Queries) GetDeployRecord(ctx context.Context, db DBTX, arg GetDeployRecordParams) (*DeployRecord, error) {
	row := db.QueryRow(ctx, getDeployRecord, arg.MonorepoID, arg.TrunkSha)
	var i DeployRecord
	err := row.Scan(
		&i.MonorepoID,
		&i.TrunkSha,
		&i.ChangeKey,
		&i.Expected,
		&i.State,
		&i.Provenance,
		&i.CreatedAt,
		&i.ReadyAt,
	)
	return &i, err
}

const listDeployImages = `-- name: ListDeployImages :many
SELECT monorepo_id, trunk_sha, image, image_ref, digest, run_url, reported_at FROM deploy_images WHERE monorepo_id = $1 AND trunk_sha = $2 ORDER BY image
`

type ListDeployImagesParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	TrunkSha   string    `json:"trunk_sha"`
}

func (q *Queries) ListDeployImages(ctx context.Context, db DBTX, arg ListDeployImagesParams) ([]*DeployImage, error) {
	rows, err := db.Query(ctx, listDeployImages, arg.MonorepoID, arg.TrunkSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DeployImage
	for rows.Next() {
		var i DeployImage
		if err := rows.Scan(
			&i.MonorepoID,
			&i.TrunkSha,
			&i.Image,
			&i.ImageRef,
			&i.Digest,
			&i.RunUrl,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeployReadyIfComplete = `-- name: MarkDeployReadyIfComplete :one
UPDATE deploy_records dr
SET state = 'ready', ready_at = now()
WHERE dr.monorepo_id = $1 AND dr.trunk_sha = $2 AND dr.state <> 'ready'
  AND NOT EXISTS (
    SELECT 1 FROM unnest(dr.expected) AS e
    WHERE NOT EXISTS (
      SELECT 1 FROM deploy_images di
      WHERE di.monorepo_id = dr.monorepo_id AND di.trunk_sha = dr.trunk_sha AND di.image = e
    )
  )
RETURNING monorepo_id, trunk_sha, change_key, expected, state, provenance, created_at, ready_at
`

type MarkDeployReadyIfCompleteParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	TrunkSha   string    `json:"trunk_sha"`
}

// Flip pending -> ready atomically, but ONLY when every expected image has a
// reported row (evaluated against committed rows at UPDATE time, so it is
// race-safe under concurrent final reports). Returns a row only on the
// transition (state <> 'ready'), so the caller emits deploy.images_ready
// exactly once.
func (q *Queries) MarkDeployReadyIfComplete(ctx context.Context, db DBTX, arg MarkDeployReadyIfCompleteParams) (*DeployRecord, error) {
	row := db.QueryRow(ctx, markDeployReadyIfComplete, arg.MonorepoID, arg.TrunkSha)
	var i DeployRecord
	err := row.Scan(
		&i.MonorepoID,
		&i.TrunkSha,
		&i.ChangeKey,
		&i.Expected,
		&i.State,
		&i.Provenance,
		&i.CreatedAt,
		&i.ReadyAt,
	)
	return &i, err
}

const openDeployRecord = `-- name: OpenDeployRecord :exec

INSERT INTO deploy_records (monorepo_id, trunk_sha, change_key, expected, provenance)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (monorepo_id, trunk_sha) DO NOTHING
`

type OpenDeployRecordParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	TrunkSha   string    `json:"trunk_sha"`
	ChangeKey  string    `json:"change_key"`
	Expected   []string  `json:"expected"`
	Provenance string    `json:"provenance"`
}

// Deploy records: the inverted CD trigger's server-of-record (§14.10). See
// db/migrations/0021_deploy_records.up.sql. Opened on land, filled by
// report-image, flipped to 'ready' when the expected image set is complete.
// Idempotent: a re-land or duplicate land event must not reset reported
// digests, so an existing record is left untouched.
func (q *Queries) OpenDeployRecord(ctx context.Context, db DBTX, arg OpenDeployRecordParams) error {
	_, err := db.Exec(ctx, openDeployRecord,
		arg.MonorepoID,
		arg.TrunkSha,
		arg.ChangeKey,
		arg.Expected,
		arg.Provenance,
	)
	return err
}

const pruneStalePendingDeployRecords = `-- name: PruneStalePendingDeployRecords :execrows
DELETE FROM deploy_records
WHERE monorepo_id = $1 AND state = 'pending' AND created_at < $2
`

type PruneStalePendingDeployRecordsParams struct {
	MonorepoID uuid.UUID          `json:"monorepo_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Drop pending records older than the cutoff. An org whose CD pins image
// digests in CI (not via report-image) never reports, so its records never
// flip to 'ready'; without this they accrue unbounded. The cutoff is generous
// (well past any real post-land build), so an in-flight report is never lost.
// deploy_images cascade-delete with the record (FK ON DELETE CASCADE).
func (q *Queries) PruneStalePendingDeployRecords(ctx context.Context, db DBTX, arg PruneStalePendingDeployRecordsParams) (int64, error) {
	result, err := db.Exec(ctx, pruneStalePendingDeployRecords, arg.MonorepoID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDeployImage = `-- name: UpsertDeployImage :exec
INSERT INTO deploy_images (monorepo_id, trunk_sha, image, image_ref, digest, run_url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (monorepo_id, trunk_sha, image)
DO UPDATE SET image_ref = EXCLUDED.image_ref, digest = EXCLUDED.digest,
             run_url = EXCLUDED.run_url, reported_at = now()
`

type UpsertDeployImageParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	TrunkSha   string    `json:"trunk_sha"`
	Image      string    `json:"image"`
	ImageRef   string    `json:"image_ref"`
	Digest     string    `json:"digest"`
	RunUrl     string    `json:"run_url"`
}

func (q *Queries) UpsertDeployImage(ctx context.Context, db DBTX, arg UpsertDeployImageParams) error {
	_, err := db.Exec(ctx, upsertDeployImage,
		arg.MonorepoID,
		arg.TrunkSha,
		arg.Image,
		arg.ImageRef,
		arg.Digest,
		arg.RunUrl,
	)
	return err
}
