// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_requests.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveInviteRequests = `-- name: CountLiveInviteRequests :one
SELECT count(*) FROM invite_requests WHERE status IN ('pending', 'failed')
`

func (q *Queries) CountLiveInviteRequests(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countLiveInviteRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInviteRequest = `-- name: CreateInviteRequest :one

INSERT INTO invite_requests (kind, name, email, message) VALUES ($1, $2, $3, $4)
ON CONFLICT (kind, lower(email)) WHERE status IN ('pending', 'failed') DO NOTHING
RETURNING id, name, email, message, status, attempt, next_attempt_at, last_error, created_at, sent_at, kind
`

type CreateInviteRequestParams struct {
	Kind    InviteRequestKind `json:"kind"`
	Name    string            `json:"name"`
	Email   string            `json:"email"`
	Message string            `json:"message"`
}

// Invite requests (§15.1, decided 2026-07-13): deployment-wide rows (no
// org column - requests precede accounts) with the webhook-outbox
// lifecycle. The mailer service drains the due feed over REST; backoff
// and dead-lettering are computed server-side (runkod/invite.go).
func (q *Queries) CreateInviteRequest(ctx context.Context, db DBTX, arg CreateInviteRequestParams) (*InviteRequest, error) {
	row := db.QueryRow(ctx, createInviteRequest,
		arg.Kind,
		arg.Name,
		arg.Email,
		arg.Message,
	)
	var i InviteRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.Kind,
	)
	return &i, err
}

const getInviteRequest = `-- name: GetInviteRequest :one
SELECT id, name, email, message, status, attempt, next_attempt_at, last_error, created_at, sent_at, kind FROM invite_requests WHERE id = $1
`

func (q *Queries) GetInviteRequest(ctx context.Context, db DBTX, id uuid.UUID) (*InviteRequest, error) {
	row := db.QueryRow(ctx, getInviteRequest, id)
	var i InviteRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.Kind,
	)
	return &i, err
}

const listDueInviteRequests = `-- name: ListDueInviteRequests :many
SELECT id, name, email, message, status, attempt, next_attempt_at, last_error, created_at, sent_at, kind FROM invite_requests
WHERE status IN ('pending', 'failed') AND next_attempt_at <= now()
ORDER BY next_attempt_at
LIMIT $1
`

func (q *Queries) ListDueInviteRequests(ctx context.Context, db DBTX, limit int32) ([]*InviteRequest, error) {
	rows, err := db.Query(ctx, listDueInviteRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*InviteRequest
	for rows.Next() {
		var i InviteRequest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.Status,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteRequestFailed = `-- name: MarkInviteRequestFailed :one
UPDATE invite_requests
SET status = $2, attempt = attempt + 1, next_attempt_at = $3, last_error = $4
WHERE id = $1 RETURNING id, name, email, message, status, attempt, next_attempt_at, last_error, created_at, sent_at, kind
`

type MarkInviteRequestFailedParams struct {
	ID            uuid.UUID           `json:"id"`
	Status        InviteRequestStatus `json:"status"`
	NextAttemptAt pgtype.Timestamptz  `json:"next_attempt_at"`
	LastError     *string             `json:"last_error"`
}

func (q *Queries) MarkInviteRequestFailed(ctx context.Context, db DBTX, arg MarkInviteRequestFailedParams) (*InviteRequest, error) {
	row := db.QueryRow(ctx, markInviteRequestFailed,
		arg.ID,
		arg.Status,
		arg.NextAttemptAt,
		arg.LastError,
	)
	var i InviteRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.Kind,
	)
	return &i, err
}

const markInviteRequestSent = `-- name: MarkInviteRequestSent :one
UPDATE invite_requests SET status = 'sent', sent_at = now() WHERE id = $1 RETURNING id, name, email, message, status, attempt, next_attempt_at, last_error, created_at, sent_at, kind
`

func (q *Queries) MarkInviteRequestSent(ctx context.Context, db DBTX, id uuid.UUID) (*InviteRequest, error) {
	row := db.QueryRow(ctx, markInviteRequestSent, id)
	var i InviteRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.Kind,
	)
	return &i, err
}
