// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mirror.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const freezeMirrorCursor = `-- name: FreezeMirrorCursor :one
INSERT INTO mirror_cursors (monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen)
VALUES ($1, $2, $3, NULL, $4, true)
ON CONFLICT (monorepo_id, remote_name, ref_name) DO UPDATE
    SET frozen = true, updated_at = now()
RETURNING id, monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen, updated_at
`

type FreezeMirrorCursorParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	RemoteName string    `json:"remote_name"`
	RefName    string    `json:"ref_name"`
	Writer     string    `json:"writer"`
}

func (q *Queries) FreezeMirrorCursor(ctx context.Context, db DBTX, arg FreezeMirrorCursorParams) (*MirrorCursor, error) {
	row := db.QueryRow(ctx, freezeMirrorCursor,
		arg.MonorepoID,
		arg.RemoteName,
		arg.RefName,
		arg.Writer,
	)
	var i MirrorCursor
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.RemoteName,
		&i.RefName,
		&i.LastSyncedSha,
		&i.Writer,
		&i.Frozen,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMirrorCursor = `-- name: GetMirrorCursor :one

SELECT id, monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen, updated_at FROM mirror_cursors WHERE monorepo_id = $1 AND remote_name = $2 AND ref_name = $3
`

type GetMirrorCursorParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	RemoteName string    `json:"remote_name"`
	RefName    string    `json:"ref_name"`
}

// Mirror cursors (§18.6): per-(remote, ref) sync state for the outbound
// mirror. writer names which side may write the ref (always 'runko' in the
// outbound M1 - the single-writer lease's bookkeeping half); frozen is
// invariant 4's loud stop. State is rebuildable from the two git histories
// (invariant 5) - these rows are cache and audit, never truth.
func (q *Queries) GetMirrorCursor(ctx context.Context, db DBTX, arg GetMirrorCursorParams) (*MirrorCursor, error) {
	row := db.QueryRow(ctx, getMirrorCursor, arg.MonorepoID, arg.RemoteName, arg.RefName)
	var i MirrorCursor
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.RemoteName,
		&i.RefName,
		&i.LastSyncedSha,
		&i.Writer,
		&i.Frozen,
		&i.UpdatedAt,
	)
	return &i, err
}

const listMirrorCursors = `-- name: ListMirrorCursors :many
SELECT id, monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen, updated_at FROM mirror_cursors WHERE monorepo_id = $1 AND remote_name = $2 ORDER BY ref_name
`

type ListMirrorCursorsParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	RemoteName string    `json:"remote_name"`
}

func (q *Queries) ListMirrorCursors(ctx context.Context, db DBTX, arg ListMirrorCursorsParams) ([]*MirrorCursor, error) {
	rows, err := db.Query(ctx, listMirrorCursors, arg.MonorepoID, arg.RemoteName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MirrorCursor
	for rows.Next() {
		var i MirrorCursor
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.RemoteName,
			&i.RefName,
			&i.LastSyncedSha,
			&i.Writer,
			&i.Frozen,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMirrorCursor = `-- name: UpsertMirrorCursor :one
INSERT INTO mirror_cursors (monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen)
VALUES ($1, $2, $3, $4, $5, false)
ON CONFLICT (monorepo_id, remote_name, ref_name) DO UPDATE
    SET last_synced_sha = EXCLUDED.last_synced_sha, frozen = false, updated_at = now()
RETURNING id, monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen, updated_at
`

type UpsertMirrorCursorParams struct {
	MonorepoID    uuid.UUID `json:"monorepo_id"`
	RemoteName    string    `json:"remote_name"`
	RefName       string    `json:"ref_name"`
	LastSyncedSha *string   `json:"last_synced_sha"`
	Writer        string    `json:"writer"`
}

func (q *Queries) UpsertMirrorCursor(ctx context.Context, db DBTX, arg UpsertMirrorCursorParams) (*MirrorCursor, error) {
	row := db.QueryRow(ctx, upsertMirrorCursor,
		arg.MonorepoID,
		arg.RemoteName,
		arg.RefName,
		arg.LastSyncedSha,
		arg.Writer,
	)
	var i MirrorCursor
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.RemoteName,
		&i.RefName,
		&i.LastSyncedSha,
		&i.Writer,
		&i.Frozen,
		&i.UpdatedAt,
	)
	return &i, err
}
