// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mirror.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const freezeMirrorCursor = `-- name: FreezeMirrorCursor :exec
UPDATE mirror_cursors SET frozen = true, updated_at = now() WHERE id = $1
`

func (q *Queries) FreezeMirrorCursor(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.Exec(ctx, freezeMirrorCursor, id)
	return err
}

const listMirrorCursors = `-- name: ListMirrorCursors :many
SELECT id, monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen, updated_at FROM mirror_cursors WHERE monorepo_id = $1
`

func (q *Queries) ListMirrorCursors(ctx context.Context, db DBTX, monorepoID uuid.UUID) ([]*MirrorCursor, error) {
	rows, err := db.Query(ctx, listMirrorCursors, monorepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MirrorCursor
	for rows.Next() {
		var i MirrorCursor
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.RemoteName,
			&i.RefName,
			&i.LastSyncedSha,
			&i.Writer,
			&i.Frozen,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMirrorCursor = `-- name: UpsertMirrorCursor :one
INSERT INTO mirror_cursors (monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (monorepo_id, remote_name, ref_name) DO UPDATE
    SET last_synced_sha = EXCLUDED.last_synced_sha,
        writer = EXCLUDED.writer,
        frozen = EXCLUDED.frozen,
        updated_at = now()
RETURNING id, monorepo_id, remote_name, ref_name, last_synced_sha, writer, frozen, updated_at
`

type UpsertMirrorCursorParams struct {
	MonorepoID    uuid.UUID `json:"monorepo_id"`
	RemoteName    string    `json:"remote_name"`
	RefName       string    `json:"ref_name"`
	LastSyncedSha *string   `json:"last_synced_sha"`
	Writer        string    `json:"writer"`
	Frozen        bool      `json:"frozen"`
}

func (q *Queries) UpsertMirrorCursor(ctx context.Context, db DBTX, arg UpsertMirrorCursorParams) (*MirrorCursor, error) {
	row := db.QueryRow(ctx, upsertMirrorCursor,
		arg.MonorepoID,
		arg.RemoteName,
		arg.RefName,
		arg.LastSyncedSha,
		arg.Writer,
		arg.Frozen,
	)
	var i MirrorCursor
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.RemoteName,
		&i.RefName,
		&i.LastSyncedSha,
		&i.Writer,
		&i.Frozen,
		&i.UpdatedAt,
	)
	return &i, err
}
