// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActorType string

const (
	ActorTypeUser  ActorType = "user"
	ActorTypeGroup ActorType = "group"
	ActorTypeAgent ActorType = "agent"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType `json:"actor_type"`
	Valid     bool      `json:"valid"` // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

type ChangeState string

const (
	ChangeStateOpen      ChangeState = "open"
	ChangeStateLanded    ChangeState = "landed"
	ChangeStateAbandoned ChangeState = "abandoned"
)

func (e *ChangeState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChangeState(s)
	case string:
		*e = ChangeState(s)
	default:
		return fmt.Errorf("unsupported scan type for ChangeState: %T", src)
	}
	return nil
}

type NullChangeState struct {
	ChangeState ChangeState `json:"change_state"`
	Valid       bool        `json:"valid"` // Valid is true if ChangeState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChangeState) Scan(value interface{}) error {
	if value == nil {
		ns.ChangeState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChangeState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChangeState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChangeState), nil
}

type CheckConclusion string

const (
	CheckConclusionSuccess        CheckConclusion = "success"
	CheckConclusionFailure        CheckConclusion = "failure"
	CheckConclusionCancelled      CheckConclusion = "cancelled"
	CheckConclusionSkipped        CheckConclusion = "skipped"
	CheckConclusionTimedOut       CheckConclusion = "timed_out"
	CheckConclusionActionRequired CheckConclusion = "action_required"
	CheckConclusionNeutral        CheckConclusion = "neutral"
)

func (e *CheckConclusion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckConclusion(s)
	case string:
		*e = CheckConclusion(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckConclusion: %T", src)
	}
	return nil
}

type NullCheckConclusion struct {
	CheckConclusion CheckConclusion `json:"check_conclusion"`
	Valid           bool            `json:"valid"` // Valid is true if CheckConclusion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckConclusion) Scan(value interface{}) error {
	if value == nil {
		ns.CheckConclusion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckConclusion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckConclusion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckConclusion), nil
}

type CheckStatus string

const (
	CheckStatusQueued     CheckStatus = "queued"
	CheckStatusInProgress CheckStatus = "in_progress"
	CheckStatusCompleted  CheckStatus = "completed"
)

func (e *CheckStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckStatus(s)
	case string:
		*e = CheckStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckStatus: %T", src)
	}
	return nil
}

type NullCheckStatus struct {
	CheckStatus CheckStatus `json:"check_status"`
	Valid       bool        `json:"valid"` // Valid is true if CheckStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CheckStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckStatus), nil
}

type WebhookDeliveryStatus string

const (
	WebhookDeliveryStatusPending    WebhookDeliveryStatus = "pending"
	WebhookDeliveryStatusDelivered  WebhookDeliveryStatus = "delivered"
	WebhookDeliveryStatusFailed     WebhookDeliveryStatus = "failed"
	WebhookDeliveryStatusDeadLetter WebhookDeliveryStatus = "dead_letter"
)

func (e *WebhookDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookDeliveryStatus(s)
	case string:
		*e = WebhookDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookDeliveryStatus: %T", src)
	}
	return nil
}

type NullWebhookDeliveryStatus struct {
	WebhookDeliveryStatus WebhookDeliveryStatus `json:"webhook_delivery_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if WebhookDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookDeliveryStatus), nil
}

type WorkspaceMode string

const (
	WorkspaceModeSparseLocal WorkspaceMode = "sparse_local"
	WorkspaceModeRemoteVm    WorkspaceMode = "remote_vm"
	WorkspaceModeJoshSlice   WorkspaceMode = "josh_slice"
)

func (e *WorkspaceMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceMode(s)
	case string:
		*e = WorkspaceMode(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceMode: %T", src)
	}
	return nil
}

type NullWorkspaceMode struct {
	WorkspaceMode WorkspaceMode `json:"workspace_mode"`
	Valid         bool          `json:"valid"` // Valid is true if WorkspaceMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceMode) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceMode), nil
}

type WorkspaceStatus string

const (
	WorkspaceStatusActive   WorkspaceStatus = "active"
	WorkspaceStatusDetached WorkspaceStatus = "detached"
	WorkspaceStatusClosed   WorkspaceStatus = "closed"
)

func (e *WorkspaceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceStatus(s)
	case string:
		*e = WorkspaceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceStatus: %T", src)
	}
	return nil
}

type NullWorkspaceStatus struct {
	WorkspaceStatus WorkspaceStatus `json:"workspace_status"`
	Valid           bool            `json:"valid"` // Valid is true if WorkspaceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceStatus), nil
}

type Actor struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	Type          ActorType          `json:"type"`
	ExternalRef   string             `json:"external_ref"`
	DisplayName   *string            `json:"display_name"`
	AgentPolicyID pgtype.UUID        `json:"agent_policy_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AgentPolicy struct {
	ID                       uuid.UUID          `json:"id"`
	OrgID                    uuid.UUID          `json:"org_id"`
	Name                     string             `json:"name"`
	RequireWorkspaceAffinity bool               `json:"require_workspace_affinity"`
	MaxChangedFiles          int32              `json:"max_changed_files"`
	MaxDiffBytes             int64              `json:"max_diff_bytes"`
	CanCreateProjects        bool               `json:"can_create_projects"`
	CanLandChanges           bool               `json:"can_land_changes"`
	CanModifyOwners          bool               `json:"can_modify_owners"`
	CanEnableCapabilities    []string           `json:"can_enable_capabilities"`
	DenylistPaths            []string           `json:"denylist_paths"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type Change struct {
	ID                uuid.UUID          `json:"id"`
	MonorepoID        uuid.UUID          `json:"monorepo_id"`
	ChangeKey         string             `json:"change_key"`
	Number            int64              `json:"number"`
	State             ChangeState        `json:"state"`
	BaseSha           string             `json:"base_sha"`
	HeadSha           string             `json:"head_sha"`
	GitRef            string             `json:"git_ref"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	TestPlan          string             `json:"test_plan"`
	AuthoredByActorID uuid.UUID          `json:"authored_by_actor_id"`
	DependsOnChangeID pgtype.UUID        `json:"depends_on_change_id"`
	Mechanical        bool               `json:"mechanical"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	LandedAt          pgtype.Timestamptz `json:"landed_at"`
	LandedSha         *string            `json:"landed_sha"`
	LandedByActorID   pgtype.UUID        `json:"landed_by_actor_id"`
	OriginWorkspace   string             `json:"origin_workspace"`
	OriginBranch      string             `json:"origin_branch"`
	LandedForced      bool               `json:"landed_forced"`
}

type ChangeAffected struct {
	ID            uuid.UUID          `json:"id"`
	ChangeID      uuid.UUID          `json:"change_id"`
	HeadSha       string             `json:"head_sha"`
	ComputationID string             `json:"computation_id"`
	RunEverything bool               `json:"run_everything"`
	ReasonCodes   []string           `json:"reason_codes"`
	ComputedAt    pgtype.Timestamptz `json:"computed_at"`
}

type ChangeAffectedProject struct {
	ChangeAffectedID uuid.UUID `json:"change_affected_id"`
	ProjectID        uuid.UUID `json:"project_id"`
}

type ChangeAssistedBy struct {
	ChangeID uuid.UUID `json:"change_id"`
	ActorID  uuid.UUID `json:"actor_id"`
}

type ChangeComment struct {
	ID            uuid.UUID          `json:"id"`
	ChangeID      uuid.UUID          `json:"change_id"`
	AuthorActorID uuid.UUID          `json:"author_actor_id"`
	Body          string             `json:"body"`
	Path          *string            `json:"path"`
	Line          *int32             `json:"line"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ChangeOwnerRequirement struct {
	ChangeID            uuid.UUID          `json:"change_id"`
	OwnerRef            string             `json:"owner_ref"`
	Satisfied           bool               `json:"satisfied"`
	SatisfiedByActorID  pgtype.UUID        `json:"satisfied_by_actor_id"`
	SatisfiedAt         pgtype.Timestamptz `json:"satisfied_at"`
	SatisfiedForHeadSha *string            `json:"satisfied_for_head_sha"`
}

type CheckAnnotation struct {
	ID              uuid.UUID `json:"id"`
	CheckRunID      uuid.UUID `json:"check_run_id"`
	Path            string    `json:"path"`
	StartLine       int32     `json:"start_line"`
	EndLine         int32     `json:"end_line"`
	AnnotationLevel string    `json:"annotation_level"`
	Message         string    `json:"message"`
	Title           *string   `json:"title"`
}

type CheckRun struct {
	ID            uuid.UUID          `json:"id"`
	ChangeID      uuid.UUID          `json:"change_id"`
	HeadSha       string             `json:"head_sha"`
	Name          string             `json:"name"`
	ExternalID    string             `json:"external_id"`
	Status        CheckStatus        `json:"status"`
	Conclusion    *CheckConclusion   `json:"conclusion"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DetailsUrl    *string            `json:"details_url"`
	OutputTitle   *string            `json:"output_title"`
	OutputSummary *string            `json:"output_summary"`
	OutputText    *string            `json:"output_text"`
	AppID         *string            `json:"app_id"`
	Reporter      string             `json:"reporter"`
	Attempt       int32              `json:"attempt"`
	TtlSeconds    int32              `json:"ttl_seconds"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type InferredDependency struct {
	ProjectID          uuid.UUID          `json:"project_id"`
	DependsOnProjectID uuid.UUID          `json:"depends_on_project_id"`
	Confidence         float32            `json:"confidence"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
}

type MirrorCursor struct {
	ID            uuid.UUID          `json:"id"`
	MonorepoID    uuid.UUID          `json:"monorepo_id"`
	RemoteName    string             `json:"remote_name"`
	RefName       string             `json:"ref_name"`
	LastSyncedSha *string            `json:"last_synced_sha"`
	Writer        string             `json:"writer"`
	Frozen        bool               `json:"frozen"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Monorepo struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	TrunkRef  string             `json:"trunk_ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Org struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Settings   []byte             `json:"settings"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type OrgMember struct {
	ID            uuid.UUID          `json:"id"`
	OrgID         uuid.UUID          `json:"org_id"`
	PrincipalName string             `json:"principal_name"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Principal struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	CredentialHash string             `json:"credential_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID                   uuid.UUID          `json:"id"`
	MonorepoID           uuid.UUID          `json:"monorepo_id"`
	Name                 string             `json:"name"`
	Path                 string             `json:"path"`
	ProjectType          string             `json:"project_type"`
	TemplateID           pgtype.UUID        `json:"template_id"`
	Visibility           string             `json:"visibility"`
	Capabilities         []string           `json:"capabilities"`
	DeclaredDependencies []string           `json:"declared_dependencies"`
	IndexedAtSha         string             `json:"indexed_at_sha"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ProjectOwner struct {
	ProjectID uuid.UUID `json:"project_id"`
	OwnerRef  string    `json:"owner_ref"`
	Source    string    `json:"source"`
}

type Template struct {
	ID                  uuid.UUID          `json:"id"`
	OrgID               uuid.UUID          `json:"org_id"`
	TemplateKey         string             `json:"template_key"`
	Name                string             `json:"name"`
	ProjectType         string             `json:"project_type"`
	Description         string             `json:"description"`
	DefaultCapabilities []string           `json:"default_capabilities"`
	Version             int32              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	ID            uuid.UUID             `json:"id"`
	OrgID         uuid.UUID             `json:"org_id"`
	DeliveryID    uuid.UUID             `json:"delivery_id"`
	EventType     string                `json:"event_type"`
	Payload       []byte                `json:"payload"`
	Status        WebhookDeliveryStatus `json:"status"`
	Attempt       int32                 `json:"attempt"`
	NextAttemptAt pgtype.Timestamptz    `json:"next_attempt_at"`
	LastError     *string               `json:"last_error"`
	CreatedAt     pgtype.Timestamptz    `json:"created_at"`
	DeliveredAt   pgtype.Timestamptz    `json:"delivered_at"`
}

type Workspace struct {
	ID               uuid.UUID          `json:"id"`
	OrgID            uuid.UUID          `json:"org_id"`
	MonorepoID       uuid.UUID          `json:"monorepo_id"`
	PrincipalActorID uuid.UUID          `json:"principal_actor_id"`
	CodingSessionID  pgtype.UUID        `json:"coding_session_id"`
	BaseRevision     string             `json:"base_revision"`
	ProjectAffinity  []string           `json:"project_affinity"`
	WriteAllowlist   []string           `json:"write_allowlist"`
	SnapshotRef      string             `json:"snapshot_ref"`
	Mode             WorkspaceMode      `json:"mode"`
	Status           WorkspaceStatus    `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
