// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createMonorepo = `-- name: CreateMonorepo :one
INSERT INTO monorepos (org_id, trunk_ref) VALUES ($1, $2) RETURNING id, org_id, trunk_ref, created_at
`

type CreateMonorepoParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	TrunkRef string    `json:"trunk_ref"`
}

func (q *Queries) CreateMonorepo(ctx context.Context, db DBTX, arg CreateMonorepoParams) (*Monorepo, error) {
	row := db.QueryRow(ctx, createMonorepo, arg.OrgID, arg.TrunkRef)
	var i Monorepo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TrunkRef,
		&i.CreatedAt,
	)
	return &i, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateOrg(ctx context.Context, db DBTX, name string) (*Org, error) {
	row := db.QueryRow(ctx, createOrg, name)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return &i, err
}

const getMonorepo = `-- name: GetMonorepo :one
SELECT id, org_id, trunk_ref, created_at FROM monorepos WHERE id = $1
`

func (q *Queries) GetMonorepo(ctx context.Context, db DBTX, id uuid.UUID) (*Monorepo, error) {
	row := db.QueryRow(ctx, getMonorepo, id)
	var i Monorepo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TrunkRef,
		&i.CreatedAt,
	)
	return &i, err
}

const getMonorepoByOrg = `-- name: GetMonorepoByOrg :one
SELECT id, org_id, trunk_ref, created_at FROM monorepos WHERE org_id = $1
`

func (q *Queries) GetMonorepoByOrg(ctx context.Context, db DBTX, orgID uuid.UUID) (*Monorepo, error) {
	row := db.QueryRow(ctx, getMonorepoByOrg, orgID)
	var i Monorepo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TrunkRef,
		&i.CreatedAt,
	)
	return &i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, created_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, db DBTX, id uuid.UUID) (*Org, error) {
	row := db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return &i, err
}

const getOrgByName = `-- name: GetOrgByName :one
SELECT id, name, created_at FROM orgs WHERE name = $1
`

func (q *Queries) GetOrgByName(ctx context.Context, db DBTX, name string) (*Org, error) {
	row := db.QueryRow(ctx, getOrgByName, name)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return &i, err
}

const listOrgs = `-- name: ListOrgs :many
SELECT id, name, created_at FROM orgs ORDER BY created_at
`

func (q *Queries) ListOrgs(ctx context.Context, db DBTX) ([]*Org, error) {
	rows, err := db.Query(ctx, listOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
