// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createMonorepo = `-- name: CreateMonorepo :one
INSERT INTO monorepos (org_id, trunk_ref) VALUES ($1, $2) RETURNING id, org_id, trunk_ref, created_at
`

type CreateMonorepoParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	TrunkRef string    `json:"trunk_ref"`
}

func (q *Queries) CreateMonorepo(ctx context.Context, db DBTX, arg CreateMonorepoParams) (*Monorepo, error) {
	row := db.QueryRow(ctx, createMonorepo, arg.OrgID, arg.TrunkRef)
	var i Monorepo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TrunkRef,
		&i.CreatedAt,
	)
	return &i, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name) VALUES ($1) RETURNING id, name, created_at, settings, archived_at
`

func (q *Queries) CreateOrg(ctx context.Context, db DBTX, name string) (*Org, error) {
	row := db.QueryRow(ctx, createOrg, name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Settings,
		&i.ArchivedAt,
	)
	return &i, err
}

const deleteOrgMember = `-- name: DeleteOrgMember :exec
DELETE FROM org_members m
USING orgs o
WHERE o.id = m.org_id AND o.name = $1::text
  AND m.principal_name = $2::text
`

type DeleteOrgMemberParams struct {
	OrgName       string `json:"org_name"`
	PrincipalName string `json:"principal_name"`
}

func (q *Queries) DeleteOrgMember(ctx context.Context, db DBTX, arg DeleteOrgMemberParams) error {
	_, err := db.Exec(ctx, deleteOrgMember, arg.OrgName, arg.PrincipalName)
	return err
}

const getMonorepo = `-- name: GetMonorepo :one
SELECT id, org_id, trunk_ref, created_at FROM monorepos WHERE id = $1
`

func (q *Queries) GetMonorepo(ctx context.Context, db DBTX, id uuid.UUID) (*Monorepo, error) {
	row := db.QueryRow(ctx, getMonorepo, id)
	var i Monorepo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TrunkRef,
		&i.CreatedAt,
	)
	return &i, err
}

const getMonorepoByOrg = `-- name: GetMonorepoByOrg :one
SELECT id, org_id, trunk_ref, created_at FROM monorepos WHERE org_id = $1
`

func (q *Queries) GetMonorepoByOrg(ctx context.Context, db DBTX, orgID uuid.UUID) (*Monorepo, error) {
	row := db.QueryRow(ctx, getMonorepoByOrg, orgID)
	var i Monorepo
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TrunkRef,
		&i.CreatedAt,
	)
	return &i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, created_at, settings, archived_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, db DBTX, id uuid.UUID) (*Org, error) {
	row := db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Settings,
		&i.ArchivedAt,
	)
	return &i, err
}

const getOrgByName = `-- name: GetOrgByName :one
SELECT id, name, created_at, settings, archived_at FROM orgs WHERE name = $1
`

func (q *Queries) GetOrgByName(ctx context.Context, db DBTX, name string) (*Org, error) {
	row := db.QueryRow(ctx, getOrgByName, name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Settings,
		&i.ArchivedAt,
	)
	return &i, err
}

const getOrgMemberRole = `-- name: GetOrgMemberRole :one
SELECT m.role FROM org_members m
JOIN orgs o ON o.id = m.org_id
WHERE o.name = $1::text AND m.principal_name = $2::text
`

type GetOrgMemberRoleParams struct {
	OrgName       string `json:"org_name"`
	PrincipalName string `json:"principal_name"`
}

func (q *Queries) GetOrgMemberRole(ctx context.Context, db DBTX, arg GetOrgMemberRoleParams) (string, error) {
	row := db.QueryRow(ctx, getOrgMemberRole, arg.OrgName, arg.PrincipalName)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getOrgSettings = `-- name: GetOrgSettings :one
SELECT settings FROM orgs WHERE name = $1::text
`

func (q *Queries) GetOrgSettings(ctx context.Context, db DBTX, orgName string) ([]byte, error) {
	row := db.QueryRow(ctx, getOrgSettings, orgName)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT m.principal_name, m.role FROM org_members m
JOIN orgs o ON o.id = m.org_id
WHERE o.name = $1::text
ORDER BY m.principal_name
`

type ListOrgMembersRow struct {
	PrincipalName string `json:"principal_name"`
	Role          string `json:"role"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, db DBTX, orgName string) ([]*ListOrgMembersRow, error) {
	rows, err := db.Query(ctx, listOrgMembers, orgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(&i.PrincipalName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembershipsForPrincipal = `-- name: ListOrgMembershipsForPrincipal :many
SELECT o.name AS org_name, m.role FROM org_members m
JOIN orgs o ON o.id = m.org_id
WHERE m.principal_name = $1::text
  AND o.archived_at IS NULL
ORDER BY o.name
`

type ListOrgMembershipsForPrincipalRow struct {
	OrgName string `json:"org_name"`
	Role    string `json:"role"`
}

func (q *Queries) ListOrgMembershipsForPrincipal(ctx context.Context, db DBTX, principalName string) ([]*ListOrgMembershipsForPrincipalRow, error) {
	rows, err := db.Query(ctx, listOrgMembershipsForPrincipal, principalName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListOrgMembershipsForPrincipalRow
	for rows.Next() {
		var i ListOrgMembershipsForPrincipalRow
		if err := rows.Scan(&i.OrgName, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgs = `-- name: ListOrgs :many
SELECT id, name, created_at, settings, archived_at FROM orgs ORDER BY created_at
`

func (q *Queries) ListOrgs(ctx context.Context, db DBTX) ([]*Org, error) {
	rows, err := db.Query(ctx, listOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Settings,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgArchived = `-- name: SetOrgArchived :exec
UPDATE orgs SET archived_at = CASE WHEN $1::boolean THEN now() ELSE NULL END
WHERE name = $2::text
`

type SetOrgArchivedParams struct {
	Archived bool   `json:"archived"`
	OrgName  string `json:"org_name"`
}

func (q *Queries) SetOrgArchived(ctx context.Context, db DBTX, arg SetOrgArchivedParams) error {
	_, err := db.Exec(ctx, setOrgArchived, arg.Archived, arg.OrgName)
	return err
}

const updateOrgSettings = `-- name: UpdateOrgSettings :exec
UPDATE orgs SET settings = $1::jsonb
WHERE name = $2::text
`

type UpdateOrgSettingsParams struct {
	Settings []byte `json:"settings"`
	OrgName  string `json:"org_name"`
}

func (q *Queries) UpdateOrgSettings(ctx context.Context, db DBTX, arg UpdateOrgSettingsParams) error {
	_, err := db.Exec(ctx, updateOrgSettings, arg.Settings, arg.OrgName)
	return err
}

const upsertOrgMember = `-- name: UpsertOrgMember :exec

INSERT INTO org_members (org_id, principal_name, role)
SELECT o.id, $1::text, $2::text
FROM orgs o WHERE o.name = $3::text
ON CONFLICT (org_id, principal_name) DO UPDATE SET role = EXCLUDED.role
`

type UpsertOrgMemberParams struct {
	PrincipalName string `json:"principal_name"`
	Role          string `json:"role"`
	OrgName       string `json:"org_name"`
}

// Org membership (db/migrations/0007): which store-backed principals may
// reach an org's /o/<name>/ surface at all. Roles: 'admin' (may add
// members) or 'member'. Operator principals and the deploy token are
// daemon config and never appear here.
func (q *Queries) UpsertOrgMember(ctx context.Context, db DBTX, arg UpsertOrgMemberParams) error {
	_, err := db.Exec(ctx, upsertOrgMember, arg.PrincipalName, arg.Role, arg.OrgName)
	return err
}
