// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principals.sql

package dbgen

import (
	"context"
)

const createPrincipal = `-- name: CreatePrincipal :one

INSERT INTO principals (name, credential_hash)
VALUES ($1, $2)
RETURNING id, name, credential_hash, created_at
`

type CreatePrincipalParams struct {
	Name           string `json:"name"`
	CredentialHash string `json:"credential_hash"`
}

// Self-service principals (§15.1 sign-up; db/migrations/0004).
// Server-global since 0007: one account, many orgs - org access lives in
// org_members (orgs.sql).
func (q *Queries) CreatePrincipal(ctx context.Context, db DBTX, arg CreatePrincipalParams) (*Principal, error) {
	row := db.QueryRow(ctx, createPrincipal, arg.Name, arg.CredentialHash)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.CreatedAt,
	)
	return &i, err
}

const getPrincipalByName = `-- name: GetPrincipalByName :one
SELECT id, name, credential_hash, created_at FROM principals
WHERE name = $1
`

func (q *Queries) GetPrincipalByName(ctx context.Context, db DBTX, name string) (*Principal, error) {
	row := db.QueryRow(ctx, getPrincipalByName, name)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialHash,
		&i.CreatedAt,
	)
	return &i, err
}
