// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principals.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createPrincipal = `-- name: CreatePrincipal :one

INSERT INTO principals (org_id, name, credential_hash)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, credential_hash, created_at
`

type CreatePrincipalParams struct {
	OrgID          uuid.UUID `json:"org_id"`
	Name           string    `json:"name"`
	CredentialHash string    `json:"credential_hash"`
}

// Self-service principals (§15.1 sign-up; db/migrations/0004).
func (q *Queries) CreatePrincipal(ctx context.Context, db DBTX, arg CreatePrincipalParams) (*Principal, error) {
	row := db.QueryRow(ctx, createPrincipal, arg.OrgID, arg.Name, arg.CredentialHash)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CredentialHash,
		&i.CreatedAt,
	)
	return &i, err
}

const getPrincipalByName = `-- name: GetPrincipalByName :one
SELECT id, org_id, name, credential_hash, created_at FROM principals
WHERE org_id = $1 AND name = $2
`

type GetPrincipalByNameParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) GetPrincipalByName(ctx context.Context, db DBTX, arg GetPrincipalByNameParams) (*Principal, error) {
	row := db.QueryRow(ctx, getPrincipalByName, arg.OrgID, arg.Name)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CredentialHash,
		&i.CreatedAt,
	)
	return &i, err
}
