// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    monorepo_id, name, path, project_type, template_id, visibility,
    capabilities, declared_dependencies, indexed_at_sha
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, monorepo_id, name, path, project_type, template_id, visibility, capabilities, declared_dependencies, indexed_at_sha, created_at, updated_at
`

type CreateProjectParams struct {
	MonorepoID           uuid.UUID   `json:"monorepo_id"`
	Name                 string      `json:"name"`
	Path                 string      `json:"path"`
	ProjectType          string      `json:"project_type"`
	TemplateID           pgtype.UUID `json:"template_id"`
	Visibility           string      `json:"visibility"`
	Capabilities         []string    `json:"capabilities"`
	DeclaredDependencies []string    `json:"declared_dependencies"`
	IndexedAtSha         string      `json:"indexed_at_sha"`
}

func (q *Queries) CreateProject(ctx context.Context, db DBTX, arg CreateProjectParams) (*Project, error) {
	row := db.QueryRow(ctx, createProject,
		arg.MonorepoID,
		arg.Name,
		arg.Path,
		arg.ProjectType,
		arg.TemplateID,
		arg.Visibility,
		arg.Capabilities,
		arg.DeclaredDependencies,
		arg.IndexedAtSha,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.Name,
		&i.Path,
		&i.ProjectType,
		&i.TemplateID,
		&i.Visibility,
		&i.Capabilities,
		&i.DeclaredDependencies,
		&i.IndexedAtSha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteProjectOwners = `-- name: DeleteProjectOwners :exec
DELETE FROM project_owners WHERE project_id = $1
`

func (q *Queries) DeleteProjectOwners(ctx context.Context, db DBTX, projectID uuid.UUID) error {
	_, err := db.Exec(ctx, deleteProjectOwners, projectID)
	return err
}

const deleteProjectsForMonorepo = `-- name: DeleteProjectsForMonorepo :exec
DELETE FROM projects WHERE monorepo_id = $1
`

func (q *Queries) DeleteProjectsForMonorepo(ctx context.Context, db DBTX, monorepoID uuid.UUID) error {
	_, err := db.Exec(ctx, deleteProjectsForMonorepo, monorepoID)
	return err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, monorepo_id, name, path, project_type, template_id, visibility, capabilities, declared_dependencies, indexed_at_sha, created_at, updated_at FROM projects WHERE monorepo_id = $1 AND name = $2
`

type GetProjectByNameParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	Name       string    `json:"name"`
}

func (q *Queries) GetProjectByName(ctx context.Context, db DBTX, arg GetProjectByNameParams) (*Project, error) {
	row := db.QueryRow(ctx, getProjectByName, arg.MonorepoID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.Name,
		&i.Path,
		&i.ProjectType,
		&i.TemplateID,
		&i.Visibility,
		&i.Capabilities,
		&i.DeclaredDependencies,
		&i.IndexedAtSha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProjectByPath = `-- name: GetProjectByPath :one
SELECT id, monorepo_id, name, path, project_type, template_id, visibility, capabilities, declared_dependencies, indexed_at_sha, created_at, updated_at FROM projects WHERE monorepo_id = $1 AND path = $2
`

type GetProjectByPathParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	Path       string    `json:"path"`
}

func (q *Queries) GetProjectByPath(ctx context.Context, db DBTX, arg GetProjectByPathParams) (*Project, error) {
	row := db.QueryRow(ctx, getProjectByPath, arg.MonorepoID, arg.Path)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.Name,
		&i.Path,
		&i.ProjectType,
		&i.TemplateID,
		&i.Visibility,
		&i.Capabilities,
		&i.DeclaredDependencies,
		&i.IndexedAtSha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertProjectOwner = `-- name: InsertProjectOwner :exec
INSERT INTO project_owners (project_id, owner_ref, source)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, owner_ref) DO UPDATE SET source = EXCLUDED.source
`

type InsertProjectOwnerParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	OwnerRef  string    `json:"owner_ref"`
	Source    string    `json:"source"`
}

func (q *Queries) InsertProjectOwner(ctx context.Context, db DBTX, arg InsertProjectOwnerParams) error {
	_, err := db.Exec(ctx, insertProjectOwner, arg.ProjectID, arg.OwnerRef, arg.Source)
	return err
}

const listInferredDependencies = `-- name: ListInferredDependencies :many
SELECT project_id, depends_on_project_id, confidence, last_seen_at FROM inferred_dependencies WHERE project_id = $1
`

func (q *Queries) ListInferredDependencies(ctx context.Context, db DBTX, projectID uuid.UUID) ([]*InferredDependency, error) {
	rows, err := db.Query(ctx, listInferredDependencies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*InferredDependency
	for rows.Next() {
		var i InferredDependency
		if err := rows.Scan(
			&i.ProjectID,
			&i.DependsOnProjectID,
			&i.Confidence,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectOwners = `-- name: ListProjectOwners :many
SELECT project_id, owner_ref, source FROM project_owners WHERE project_id = $1
`

func (q *Queries) ListProjectOwners(ctx context.Context, db DBTX, projectID uuid.UUID) ([]*ProjectOwner, error) {
	rows, err := db.Query(ctx, listProjectOwners, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ProjectOwner
	for rows.Next() {
		var i ProjectOwner
		if err := rows.Scan(&i.ProjectID, &i.OwnerRef, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, monorepo_id, name, path, project_type, template_id, visibility, capabilities, declared_dependencies, indexed_at_sha, created_at, updated_at FROM projects
WHERE monorepo_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2::text || '%' OR path ILIKE '%' || $2::text || '%')
ORDER BY name
LIMIT $3 OFFSET $4
`

type ListProjectsParams struct {
	MonorepoID uuid.UUID `json:"monorepo_id"`
	Column2    string    `json:"column_2"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, db DBTX, arg ListProjectsParams) ([]*Project, error) {
	rows, err := db.Query(ctx, listProjects,
		arg.MonorepoID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.Name,
			&i.Path,
			&i.ProjectType,
			&i.TemplateID,
			&i.Visibility,
			&i.Capabilities,
			&i.DeclaredDependencies,
			&i.IndexedAtSha,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInferredDependency = `-- name: UpsertInferredDependency :exec
INSERT INTO inferred_dependencies (project_id, depends_on_project_id, confidence, last_seen_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (project_id, depends_on_project_id) DO UPDATE
    SET confidence = EXCLUDED.confidence, last_seen_at = now()
`

type UpsertInferredDependencyParams struct {
	ProjectID          uuid.UUID `json:"project_id"`
	DependsOnProjectID uuid.UUID `json:"depends_on_project_id"`
	Confidence         float32   `json:"confidence"`
}

func (q *Queries) UpsertInferredDependency(ctx context.Context, db DBTX, arg UpsertInferredDependencyParams) error {
	_, err := db.Exec(ctx, upsertInferredDependency, arg.ProjectID, arg.DependsOnProjectID, arg.Confidence)
	return err
}
