// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createRelease = `-- name: CreateRelease :one

INSERT INTO releases (monorepo_id, project_name, project_path, version, tag_ref, tag_sha, target_sha, head_change_key, changelog, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, monorepo_id, project_name, project_path, version, tag_ref, tag_sha, target_sha, head_change_key, changelog, created_by, created_at
`

type CreateReleaseParams struct {
	MonorepoID    uuid.UUID `json:"monorepo_id"`
	ProjectName   string    `json:"project_name"`
	ProjectPath   string    `json:"project_path"`
	Version       string    `json:"version"`
	TagRef        string    `json:"tag_ref"`
	TagSha        string    `json:"tag_sha"`
	TargetSha     string    `json:"target_sha"`
	HeadChangeKey string    `json:"head_change_key"`
	Changelog     string    `json:"changelog"`
	CreatedBy     string    `json:"created_by"`
}

// Releases (§14.10.3, stage 17b). Deliberately no UPDATE/DELETE: releases
// are immutable by construction; the UNIQUE(monorepo_id, project_name,
// version) constraint backstops concurrent same-version creates.
func (q *Queries) CreateRelease(ctx context.Context, db DBTX, arg CreateReleaseParams) (*Release, error) {
	row := db.QueryRow(ctx, createRelease,
		arg.MonorepoID,
		arg.ProjectName,
		arg.ProjectPath,
		arg.Version,
		arg.TagRef,
		arg.TagSha,
		arg.TargetSha,
		arg.HeadChangeKey,
		arg.Changelog,
		arg.CreatedBy,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ProjectName,
		&i.ProjectPath,
		&i.Version,
		&i.TagRef,
		&i.TagSha,
		&i.TargetSha,
		&i.HeadChangeKey,
		&i.Changelog,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const getLatestReleaseByProject = `-- name: GetLatestReleaseByProject :one
SELECT id, monorepo_id, project_name, project_path, version, tag_ref, tag_sha, target_sha, head_change_key, changelog, created_by, created_at FROM releases WHERE monorepo_id = $1 AND project_name = $2
ORDER BY created_at DESC LIMIT 1
`

type GetLatestReleaseByProjectParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	ProjectName string    `json:"project_name"`
}

func (q *Queries) GetLatestReleaseByProject(ctx context.Context, db DBTX, arg GetLatestReleaseByProjectParams) (*Release, error) {
	row := db.QueryRow(ctx, getLatestReleaseByProject, arg.MonorepoID, arg.ProjectName)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.MonorepoID,
		&i.ProjectName,
		&i.ProjectPath,
		&i.Version,
		&i.TagRef,
		&i.TagSha,
		&i.TargetSha,
		&i.HeadChangeKey,
		&i.Changelog,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const listReleasesByProject = `-- name: ListReleasesByProject :many
SELECT id, monorepo_id, project_name, project_path, version, tag_ref, tag_sha, target_sha, head_change_key, changelog, created_by, created_at FROM releases WHERE monorepo_id = $1 AND project_name = $2
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListReleasesByProjectParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	ProjectName string    `json:"project_name"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListReleasesByProject(ctx context.Context, db DBTX, arg ListReleasesByProjectParams) ([]*Release, error) {
	rows, err := db.Query(ctx, listReleasesByProject,
		arg.MonorepoID,
		arg.ProjectName,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.MonorepoID,
			&i.ProjectName,
			&i.ProjectPath,
			&i.Version,
			&i.TagRef,
			&i.TagSha,
			&i.TargetSha,
			&i.HeadChangeKey,
			&i.Changelog,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
