// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (org_id, template_key, name, project_type, description, default_capabilities, version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, template_key, name, project_type, description, default_capabilities, version, created_at
`

type CreateTemplateParams struct {
	OrgID               uuid.UUID `json:"org_id"`
	TemplateKey         string    `json:"template_key"`
	Name                string    `json:"name"`
	ProjectType         string    `json:"project_type"`
	Description         string    `json:"description"`
	DefaultCapabilities []string  `json:"default_capabilities"`
	Version             int32     `json:"version"`
}

func (q *Queries) CreateTemplate(ctx context.Context, db DBTX, arg CreateTemplateParams) (*Template, error) {
	row := db.QueryRow(ctx, createTemplate,
		arg.OrgID,
		arg.TemplateKey,
		arg.Name,
		arg.ProjectType,
		arg.Description,
		arg.DefaultCapabilities,
		arg.Version,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateKey,
		&i.Name,
		&i.ProjectType,
		&i.Description,
		&i.DefaultCapabilities,
		&i.Version,
		&i.CreatedAt,
	)
	return &i, err
}

const getTemplateByKey = `-- name: GetTemplateByKey :one
SELECT id, org_id, template_key, name, project_type, description, default_capabilities, version, created_at FROM templates WHERE org_id = $1 AND template_key = $2
`

type GetTemplateByKeyParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	TemplateKey string    `json:"template_key"`
}

func (q *Queries) GetTemplateByKey(ctx context.Context, db DBTX, arg GetTemplateByKeyParams) (*Template, error) {
	row := db.QueryRow(ctx, getTemplateByKey, arg.OrgID, arg.TemplateKey)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TemplateKey,
		&i.Name,
		&i.ProjectType,
		&i.Description,
		&i.DefaultCapabilities,
		&i.Version,
		&i.CreatedAt,
	)
	return &i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, org_id, template_key, name, project_type, description, default_capabilities, version, created_at FROM templates WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListTemplates(ctx context.Context, db DBTX, orgID uuid.UUID) ([]*Template, error) {
	rows, err := db.Query(ctx, listTemplates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TemplateKey,
			&i.Name,
			&i.ProjectType,
			&i.Description,
			&i.DefaultCapabilities,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
