// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueWebhookDelivery = `-- name: EnqueueWebhookDelivery :one
INSERT INTO webhook_deliveries (org_id, event_type, payload) VALUES ($1, $2, $3) RETURNING id, org_id, delivery_id, event_type, payload, status, attempt, next_attempt_at, last_error, created_at, delivered_at
`

type EnqueueWebhookDeliveryParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
}

func (q *Queries) EnqueueWebhookDelivery(ctx context.Context, db DBTX, arg EnqueueWebhookDeliveryParams) (*WebhookDelivery, error) {
	row := db.QueryRow(ctx, enqueueWebhookDelivery, arg.OrgID, arg.EventType, arg.Payload)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeliveryID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return &i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, org_id, delivery_id, event_type, payload, status, attempt, next_attempt_at, last_error, created_at, delivered_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, db DBTX, id uuid.UUID) (*WebhookDelivery, error) {
	row := db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeliveryID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return &i, err
}

const listDueWebhookDeliveries = `-- name: ListDueWebhookDeliveries :many
SELECT id, org_id, delivery_id, event_type, payload, status, attempt, next_attempt_at, last_error, created_at, delivered_at FROM webhook_deliveries
WHERE status IN ('pending', 'failed') AND next_attempt_at <= now()
ORDER BY next_attempt_at
LIMIT $1
`

func (q *Queries) ListDueWebhookDeliveries(ctx context.Context, db DBTX, limit int32) ([]*WebhookDelivery, error) {
	rows, err := db.Query(ctx, listDueWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeliveryID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE webhook_deliveries SET status = 'delivered', delivered_at = now() WHERE id = $1
`

func (q *Queries) MarkWebhookDelivered(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.Exec(ctx, markWebhookDelivered, id)
	return err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE webhook_deliveries
SET status = $2, attempt = attempt + 1, next_attempt_at = $3, last_error = $4
WHERE id = $1
`

type MarkWebhookFailedParams struct {
	ID            uuid.UUID             `json:"id"`
	Status        WebhookDeliveryStatus `json:"status"`
	NextAttemptAt pgtype.Timestamptz    `json:"next_attempt_at"`
	LastError     *string               `json:"last_error"`
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, db DBTX, arg MarkWebhookFailedParams) error {
	_, err := db.Exec(ctx, markWebhookFailed,
		arg.ID,
		arg.Status,
		arg.NextAttemptAt,
		arg.LastError,
	)
	return err
}
