// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    org_id, monorepo_id, principal_actor_id, coding_session_id, base_revision,
    project_affinity, write_allowlist, snapshot_ref, mode, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, org_id, monorepo_id, principal_actor_id, coding_session_id, base_revision, project_affinity, write_allowlist, snapshot_ref, mode, status, created_at, updated_at
`

type CreateWorkspaceParams struct {
	OrgID            uuid.UUID       `json:"org_id"`
	MonorepoID       uuid.UUID       `json:"monorepo_id"`
	PrincipalActorID uuid.UUID       `json:"principal_actor_id"`
	CodingSessionID  pgtype.UUID     `json:"coding_session_id"`
	BaseRevision     string          `json:"base_revision"`
	ProjectAffinity  []string        `json:"project_affinity"`
	WriteAllowlist   []string        `json:"write_allowlist"`
	SnapshotRef      string          `json:"snapshot_ref"`
	Mode             WorkspaceMode   `json:"mode"`
	Status           WorkspaceStatus `json:"status"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, db DBTX, arg CreateWorkspaceParams) (*Workspace, error) {
	row := db.QueryRow(ctx, createWorkspace,
		arg.OrgID,
		arg.MonorepoID,
		arg.PrincipalActorID,
		arg.CodingSessionID,
		arg.BaseRevision,
		arg.ProjectAffinity,
		arg.WriteAllowlist,
		arg.SnapshotRef,
		arg.Mode,
		arg.Status,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.MonorepoID,
		&i.PrincipalActorID,
		&i.CodingSessionID,
		&i.BaseRevision,
		&i.ProjectAffinity,
		&i.WriteAllowlist,
		&i.SnapshotRef,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

// Hard delete (workspace deletion, stage 15+): the registry row is
// metadata only (§12.2) - content durability is the snapshot refs, which
// the caller deletes alongside. A deleted id becomes reusable.
func (q *Queries) DeleteWorkspace(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, org_id, monorepo_id, principal_actor_id, coding_session_id, base_revision, project_affinity, write_allowlist, snapshot_ref, mode, status, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, db DBTX, id uuid.UUID) (*Workspace, error) {
	row := db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.MonorepoID,
		&i.PrincipalActorID,
		&i.CodingSessionID,
		&i.BaseRevision,
		&i.ProjectAffinity,
		&i.WriteAllowlist,
		&i.SnapshotRef,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWorkspaceBySnapshotRef = `-- name: GetWorkspaceBySnapshotRef :one
SELECT id, org_id, monorepo_id, principal_actor_id, coding_session_id, base_revision, project_affinity, write_allowlist, snapshot_ref, mode, status, created_at, updated_at FROM workspaces WHERE monorepo_id = $1 AND snapshot_ref = $2
`

type GetWorkspaceBySnapshotRefParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	SnapshotRef string    `json:"snapshot_ref"`
}

func (q *Queries) GetWorkspaceBySnapshotRef(ctx context.Context, db DBTX, arg GetWorkspaceBySnapshotRefParams) (*Workspace, error) {
	row := db.QueryRow(ctx, getWorkspaceBySnapshotRef, arg.MonorepoID, arg.SnapshotRef)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.MonorepoID,
		&i.PrincipalActorID,
		&i.CodingSessionID,
		&i.BaseRevision,
		&i.ProjectAffinity,
		&i.WriteAllowlist,
		&i.SnapshotRef,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listWorkspacesByMonorepo = `-- name: ListWorkspacesByMonorepo :many
SELECT id, org_id, monorepo_id, principal_actor_id, coding_session_id, base_revision, project_affinity, write_allowlist, snapshot_ref, mode, status, created_at, updated_at FROM workspaces WHERE monorepo_id = $1 ORDER BY created_at
`

func (q *Queries) ListWorkspacesByMonorepo(ctx context.Context, db DBTX, monorepoID uuid.UUID) ([]*Workspace, error) {
	rows, err := db.Query(ctx, listWorkspacesByMonorepo, monorepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.MonorepoID,
			&i.PrincipalActorID,
			&i.CodingSessionID,
			&i.BaseRevision,
			&i.ProjectAffinity,
			&i.WriteAllowlist,
			&i.SnapshotRef,
			&i.Mode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByPrincipal = `-- name: ListWorkspacesByPrincipal :many
SELECT id, org_id, monorepo_id, principal_actor_id, coding_session_id, base_revision, project_affinity, write_allowlist, snapshot_ref, mode, status, created_at, updated_at FROM workspaces WHERE principal_actor_id = $1 AND status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByPrincipal(ctx context.Context, db DBTX, principalActorID uuid.UUID) ([]*Workspace, error) {
	rows, err := db.Query(ctx, listWorkspacesByPrincipal, principalActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.MonorepoID,
			&i.PrincipalActorID,
			&i.CodingSessionID,
			&i.BaseRevision,
			&i.ProjectAffinity,
			&i.WriteAllowlist,
			&i.SnapshotRef,
			&i.Mode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceBase = `-- name: UpdateWorkspaceBase :one
UPDATE workspaces SET base_revision = $2, updated_at = now() WHERE id = $1 RETURNING id, org_id, monorepo_id, principal_actor_id, coding_session_id, base_revision, project_affinity, write_allowlist, snapshot_ref, mode, status, created_at, updated_at
`

type UpdateWorkspaceBaseParams struct {
	ID           uuid.UUID `json:"id"`
	BaseRevision string    `json:"base_revision"`
}

func (q *Queries) UpdateWorkspaceBase(ctx context.Context, db DBTX, arg UpdateWorkspaceBaseParams) (*Workspace, error) {
	row := db.QueryRow(ctx, updateWorkspaceBase, arg.ID, arg.BaseRevision)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.MonorepoID,
		&i.PrincipalActorID,
		&i.CodingSessionID,
		&i.BaseRevision,
		&i.ProjectAffinity,
		&i.WriteAllowlist,
		&i.SnapshotRef,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :one
UPDATE workspaces SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, org_id, monorepo_id, principal_actor_id, coding_session_id, base_revision, project_affinity, write_allowlist, snapshot_ref, mode, status, created_at, updated_at
`

type UpdateWorkspaceStatusParams struct {
	ID     uuid.UUID       `json:"id"`
	Status WorkspaceStatus `json:"status"`
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, db DBTX, arg UpdateWorkspaceStatusParams) (*Workspace, error) {
	row := db.QueryRow(ctx, updateWorkspaceStatus, arg.ID, arg.Status)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.MonorepoID,
		&i.PrincipalActorID,
		&i.CodingSessionID,
		&i.BaseRevision,
		&i.ProjectAffinity,
		&i.WriteAllowlist,
		&i.SnapshotRef,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
