// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_activity.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkspaceActivity = `-- name: DeleteWorkspaceActivity :exec
DELETE FROM workspace_activity WHERE monorepo_id = $1 AND workspace_id = $2
`

type DeleteWorkspaceActivityParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	WorkspaceID string    `json:"workspace_id"`
}

func (q *Queries) DeleteWorkspaceActivity(ctx context.Context, db DBTX, arg DeleteWorkspaceActivityParams) error {
	_, err := db.Exec(ctx, deleteWorkspaceActivity, arg.MonorepoID, arg.WorkspaceID)
	return err
}

const insertWorkspaceActivity = `-- name: InsertWorkspaceActivity :one

INSERT INTO workspace_activity (org_id, monorepo_id, workspace_id, actor, kind, detail, session_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, org_id, monorepo_id, workspace_id, actor, kind, detail, session_id, occurred_at
`

type InsertWorkspaceActivityParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	WorkspaceID string    `json:"workspace_id"`
	Actor       string    `json:"actor"`
	Kind        string    `json:"kind"`
	Detail      string    `json:"detail"`
	SessionID   string    `json:"session_id"`
}

// Agent session activity (§12.6.1): client-claimed, observability-only.
// The store's RecordWorkspaceActivity prunes to the retention cap after
// every batch; DeleteWorkspaceActivity rides workspace delete (close
// keeps the feed).
func (q *Queries) InsertWorkspaceActivity(ctx context.Context, db DBTX, arg InsertWorkspaceActivityParams) (*WorkspaceActivity, error) {
	row := db.QueryRow(ctx, insertWorkspaceActivity,
		arg.OrgID,
		arg.MonorepoID,
		arg.WorkspaceID,
		arg.Actor,
		arg.Kind,
		arg.Detail,
		arg.SessionID,
	)
	var i WorkspaceActivity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.MonorepoID,
		&i.WorkspaceID,
		&i.Actor,
		&i.Kind,
		&i.Detail,
		&i.SessionID,
		&i.OccurredAt,
	)
	return &i, err
}

const latestWorkspaceActivity = `-- name: LatestWorkspaceActivity :many
SELECT DISTINCT ON (workspace_id) id, org_id, monorepo_id, workspace_id, actor, kind, detail, session_id, occurred_at FROM workspace_activity
WHERE monorepo_id = $1 AND workspace_id = ANY($2::text[])
ORDER BY workspace_id, id DESC
`

type LatestWorkspaceActivityParams struct {
	MonorepoID   uuid.UUID `json:"monorepo_id"`
	WorkspaceIds []string  `json:"workspace_ids"`
}

func (q *Queries) LatestWorkspaceActivity(ctx context.Context, db DBTX, arg LatestWorkspaceActivityParams) ([]*WorkspaceActivity, error) {
	rows, err := db.Query(ctx, latestWorkspaceActivity, arg.MonorepoID, arg.WorkspaceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkspaceActivity
	for rows.Next() {
		var i WorkspaceActivity
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.MonorepoID,
			&i.WorkspaceID,
			&i.Actor,
			&i.Kind,
			&i.Detail,
			&i.SessionID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceActivity = `-- name: ListWorkspaceActivity :many
SELECT id, org_id, monorepo_id, workspace_id, actor, kind, detail, session_id, occurred_at FROM workspace_activity WHERE monorepo_id = $1 AND workspace_id = $2
ORDER BY id DESC LIMIT $3 OFFSET $4
`

type ListWorkspaceActivityParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	WorkspaceID string    `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListWorkspaceActivity(ctx context.Context, db DBTX, arg ListWorkspaceActivityParams) ([]*WorkspaceActivity, error) {
	rows, err := db.Query(ctx, listWorkspaceActivity,
		arg.MonorepoID,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkspaceActivity
	for rows.Next() {
		var i WorkspaceActivity
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.MonorepoID,
			&i.WorkspaceID,
			&i.Actor,
			&i.Kind,
			&i.Detail,
			&i.SessionID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneWorkspaceActivity = `-- name: PruneWorkspaceActivity :exec
DELETE FROM workspace_activity
WHERE workspace_activity.monorepo_id = $1 AND workspace_activity.workspace_id = $2
  AND workspace_activity.id NOT IN (
    SELECT wa.id FROM workspace_activity wa
    WHERE wa.monorepo_id = $1 AND wa.workspace_id = $2
    ORDER BY wa.id DESC LIMIT $3
)
`

type PruneWorkspaceActivityParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	WorkspaceID string    `json:"workspace_id"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) PruneWorkspaceActivity(ctx context.Context, db DBTX, arg PruneWorkspaceActivityParams) error {
	_, err := db.Exec(ctx, pruneWorkspaceActivity, arg.MonorepoID, arg.WorkspaceID, arg.Limit)
	return err
}
