// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_events.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkspaceEvents = `-- name: DeleteWorkspaceEvents :exec
DELETE FROM workspace_events WHERE monorepo_id = $1 AND workspace_id = $2
`

type DeleteWorkspaceEventsParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	WorkspaceID string    `json:"workspace_id"`
}

func (q *Queries) DeleteWorkspaceEvents(ctx context.Context, db DBTX, arg DeleteWorkspaceEventsParams) error {
	_, err := db.Exec(ctx, deleteWorkspaceEvents, arg.MonorepoID, arg.WorkspaceID)
	return err
}

const insertWorkspaceEvent = `-- name: InsertWorkspaceEvent :one

INSERT INTO workspace_events (org_id, monorepo_id, workspace_id, branch, event_type, actor, sha, change_key, files_changed, additions, deletions)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, org_id, monorepo_id, workspace_id, branch, event_type, actor, sha, change_key, files_changed, additions, deletions, occurred_at
`

type InsertWorkspaceEventParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	MonorepoID   uuid.UUID `json:"monorepo_id"`
	WorkspaceID  string    `json:"workspace_id"`
	Branch       string    `json:"branch"`
	EventType    string    `json:"event_type"`
	Actor        string    `json:"actor"`
	Sha          string    `json:"sha"`
	ChangeKey    string    `json:"change_key"`
	FilesChanged int32     `json:"files_changed"`
	Additions    int32     `json:"additions"`
	Deletions    int32     `json:"deletions"`
}

// Workspace activity timeline (§12.6): stats-only, never file content.
// History is bounded per workspace: the store's RecordWorkspaceEvent
// prunes to the retention cap after every insert; DeleteWorkspaceEvents
// rides workspace delete (close keeps the timeline).
func (q *Queries) InsertWorkspaceEvent(ctx context.Context, db DBTX, arg InsertWorkspaceEventParams) (*WorkspaceEvent, error) {
	row := db.QueryRow(ctx, insertWorkspaceEvent,
		arg.OrgID,
		arg.MonorepoID,
		arg.WorkspaceID,
		arg.Branch,
		arg.EventType,
		arg.Actor,
		arg.Sha,
		arg.ChangeKey,
		arg.FilesChanged,
		arg.Additions,
		arg.Deletions,
	)
	var i WorkspaceEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.MonorepoID,
		&i.WorkspaceID,
		&i.Branch,
		&i.EventType,
		&i.Actor,
		&i.Sha,
		&i.ChangeKey,
		&i.FilesChanged,
		&i.Additions,
		&i.Deletions,
		&i.OccurredAt,
	)
	return &i, err
}

const listWorkspaceEvents = `-- name: ListWorkspaceEvents :many
SELECT id, org_id, monorepo_id, workspace_id, branch, event_type, actor, sha, change_key, files_changed, additions, deletions, occurred_at FROM workspace_events WHERE monorepo_id = $1 AND workspace_id = $2
ORDER BY id DESC LIMIT $3 OFFSET $4
`

type ListWorkspaceEventsParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	WorkspaceID string    `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListWorkspaceEvents(ctx context.Context, db DBTX, arg ListWorkspaceEventsParams) ([]*WorkspaceEvent, error) {
	rows, err := db.Query(ctx, listWorkspaceEvents,
		arg.MonorepoID,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkspaceEvent
	for rows.Next() {
		var i WorkspaceEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.MonorepoID,
			&i.WorkspaceID,
			&i.Branch,
			&i.EventType,
			&i.Actor,
			&i.Sha,
			&i.ChangeKey,
			&i.FilesChanged,
			&i.Additions,
			&i.Deletions,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneWorkspaceEvents = `-- name: PruneWorkspaceEvents :exec
DELETE FROM workspace_events
WHERE workspace_events.monorepo_id = $1 AND workspace_events.workspace_id = $2
  AND workspace_events.id NOT IN (
    SELECT we.id FROM workspace_events we
    WHERE we.monorepo_id = $1 AND we.workspace_id = $2
    ORDER BY we.id DESC LIMIT $3
)
`

type PruneWorkspaceEventsParams struct {
	MonorepoID  uuid.UUID `json:"monorepo_id"`
	WorkspaceID string    `json:"workspace_id"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) PruneWorkspaceEvents(ctx context.Context, db DBTX, arg PruneWorkspaceEventsParams) error {
	_, err := db.Exec(ctx, pruneWorkspaceEvents, arg.MonorepoID, arg.WorkspaceID, arg.Limit)
	return err
}
