package agentsmd

import (
	"fmt"
	"strings"
)

// Command is one CLI subcommand's entry in the generated inventory.
type Command struct {
	Binary      string // "runko" or "runko-ci"
	Usage       string // e.g. "project create --name <n> --type <t>"
	Description string
	JSONOutput  string // "" if the command has no --json output
}

// Commands is the CLI command inventory, kept in sync with
// docs/cli-contract.md's table by hand (both describe the same commands;
// this one renders into AGENTS.md, that one is the human-facing doc) - see
// TestCommandsMatchesCLIContract, which fails if the two ever drift.
var Commands = []Command{
	{"runko", "doctor [--install-hook] [--json]", "check remotes/hooks, print a cheat-sheet (§6.9)", "DoctorReport"},
	{"runko", "project create --name <n> --type <t> [--owners a,b] [--json]", "create a project from an intent (§10.1)", `{"name","path","rev"}`},
	{"runko", "change push [--remote origin] [--trunk main] [--json]", "ensure a Change-Id trailer, push to refs/for/<trunk> (§11.5)", `{"change_id","ref"}`},
	{"runko", "change land --change <id> --runkod-url <url> --token <t> [--json]", "land a mergeable change onto trunk (§13.5) - needs a live runkod", "land.Outcome"},
	{"runko", "change approve --change <id> --owner <ref> --by <who> --runkod-url <url> --token <t> [--json]", "record a required owner's approval (§13.5) - needs a live runkod", "MergeRequirements"},
	{"runko", "workspace create --name <n> --project <p> --by <who> --runkod-url <url> --token <t> [--json]", "worktree + sparse cone + registry row (§12.3) - needs a live runkod", "WorkspaceInfo"},
	{"runko", "workspace list --runkod-url <url> --token <t> [--json]", "list workstreams, their cones and base revisions - needs a live runkod", "[]WorkspaceInfo"},
	{"runko", "workspace attach <id> --runkod-url <url> --token <t> [--json]", "restore a workspace from its snapshot ref (§12.2) - needs a live runkod", "WorkspaceInfo"},
	{"runko", "workspace snapshot [--dir .] [-m <msg>] [--json]", "make WIP durable: commit -> refs/workspaces/<id>/head (§12.2)", `{"ref"}`},
	{"runko", "workspace update-base --runkod-url <url> --token <t> [--dir .] [--json]", "fetch + rebase onto trunk tip, record the new base (§12.3) - needs a live runkod", `{"base_revision"}`},
	{"runko", "agents-md [--out AGENTS.md] [--json]", "regenerate this file from the CLI's own command inventory (§8.8)", `{"path"}`},
	{"runko-ci", "affected --base <rev> [--head HEAD] [--engine bazel]", "compute the affected project set for a base..head range (§13.3)", "affected.Result (always JSON)"},
	{"runko-ci", "checkout --remote <url> --dest <dir> --rev <rev> [--json]", "partial-clone + sparse-checkout a rev for CI (§14.4.4)", `{"rev","dest"}`},
	{"runko-ci", "report-check --url <u> --name <n> --external-id <id> --reporter <r> [--json]", "POST a CheckRun result to the Checks API (§14.4.1)", `{"name","status","external_id"}`},
}

// Generate renders AGENTS.md's content: static orientation bullets (§8.8's
// example snippet), the Commands table, the exit-code contract, and the
// §6.5 structured-error shape - everything an agent needs to use this CLI
// correctly without reading source.
func Generate() string {
	var b strings.Builder

	b.WriteString("# Monorepo agent instructions (generated by `runko agents-md`)\n\n")
	b.WriteString("This file is generated from the CLI's own command inventory - regenerate\n")
	b.WriteString("with `runko agents-md` after a CLI change, don't hand-edit it.\n\n")

	b.WriteString("## Orientation\n\n")
	for _, line := range []string{
		"Use the `runko`/`runko-ci` CLI (`--json` output); do not full-clone.",
		"Prefer `runko project create` over hand-authoring PROJECT.yaml.",
		"Stay within workspace affinity; use `runko-ci checkout` for deps/prefetch.",
		"Open a Change (`runko change push`) before large refactors; respect who_owns.",
	} {
		fmt.Fprintf(&b, "- %s\n", line)
	}
	b.WriteString("\n")

	b.WriteString("## Commands\n\n")
	b.WriteString("| Command | Does | `--json` output |\n")
	b.WriteString("|---|---|---|\n")
	for _, c := range Commands {
		jsonOut := c.JSONOutput
		if jsonOut == "" {
			jsonOut = "(none)"
		}
		fmt.Fprintf(&b, "| `%s %s` | %s | `%s` |\n", c.Binary, c.Usage, c.Description, jsonOut)
	}
	b.WriteString("\n")

	b.WriteString("## Exit codes\n\n")
	b.WriteString("| Code | Meaning |\n|---|---|\n")
	b.WriteString("| `0` | Success |\n")
	b.WriteString("| `1` | Command understood but failed - a structured error is printed to stderr |\n")
	b.WriteString("| `2` | Usage error - unknown command, wrong subcommand, or unparseable flags |\n\n")

	b.WriteString("## Structured errors (§6.5)\n\n")
	b.WriteString("Errors with a known cause print as:\n\n")
	b.WriteString("```text\n<message>\n  -> <suggestion>\n  see <doc_url>\n```\n\n")
	b.WriteString("to stderr, exit code `1`. Read `<suggestion>` before retrying - it names\n")
	b.WriteString("the exact next command or fix, not a generic hint.\n\n")

	b.WriteString("Full contract, including per-command flag details: `docs/cli-contract.md`.\n")

	return b.String()
}
